package solutions.thex.smoothy.generator.spring.main.src.java.security.filter;

import org.springframework.http.HttpStatus;
import solutions.thex.smoothy.code.java.declaration.JavaMethodDeclaration;
import solutions.thex.smoothy.code.java.expression.JavaMethodInvocationExpression;
import solutions.thex.smoothy.code.java.expression.JavaNewInstanceExpression;
import solutions.thex.smoothy.code.java.expression.JavaValueExpression;
import solutions.thex.smoothy.code.java.expression.JavaVariableExpression;
import solutions.thex.smoothy.code.java.expression.util.JavaMethodInvoke;
import solutions.thex.smoothy.code.java.source.JavaCompilationUnit;
import solutions.thex.smoothy.code.java.source.JavaTypeDeclaration;
import solutions.thex.smoothy.code.java.statement.JavaDeclarationStatement;
import solutions.thex.smoothy.code.java.statement.JavaExpressionStatement;
import solutions.thex.smoothy.code.java.statement.JavaTryStatement;
import solutions.thex.smoothy.code.java.util.JavaAnnotation;
import solutions.thex.smoothy.code.java.util.JavaModifier;
import solutions.thex.smoothy.code.java.util.JavaType;

import java.lang.reflect.Modifier;
import java.util.List;

public class ExceptionHandlerFilterGenerator {

    public static JavaCompilationUnit generate(String name) {
        return JavaCompilationUnit.builder()//
                .packageName("website.smoothy.".concat(name.toLowerCase()).concat(".security.filter"))//
                .name("ExceptionHandlerFilter")//
                .typeDeclarations(List.of(//
                        JavaTypeDeclaration.builder()//
                                .type(JavaType.CLASS)//
                                .name("ExceptionHandlerFilter")//
                                .modifiers(JavaModifier.builder()//
                                        .type(JavaModifier.TYPE_MODIFIERS)//
                                        .modifiers(Modifier.PUBLIC)//
                                        .build())//
                                .extendedClassName("org.springframework.web.filter.OncePerRequestFilter")//
                                .annotations(List.of(//
                                        JavaAnnotation.builder()//
                                                .name("lombok.extern.slf4j.Slf4j")//
                                                .build(),//
                                        JavaAnnotation.builder()//
                                                .name("org.springframework.stereotype.Service")//
                                                .build()))//
                                .methodDeclarations(List.of(//
                                        JavaMethodDeclaration.builder()//
                                                .name("doFilterInternal")//
                                                .returnType("void")//
                                                .modifiers(JavaModifier.builder()//
                                                        .type(JavaModifier.METHOD_MODIFIERS)//
                                                        .modifiers(Modifier.PROTECTED)//
                                                        .build())//
                                                .annotations(List.of(//
                                                        JavaAnnotation.builder()//
                                                                .name("Override")//
                                                                .build()))//
                                                .parameters(List.of(//
                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                .name("req")//
                                                                .type("javax.servlet.http.HttpServletRequest")//
                                                                .build(),//
                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                .name("res")//
                                                                .type("javax.servlet.http.HttpServletResponse")//
                                                                .build(),//
                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                .name("chain")//
                                                                .type("javax.servlet.FilterChain")//
                                                                .build()))//
                                                .isThrows(true)//
                                                .exceptions(List.of("java.io.IOException", "javax.servlet.ServletException"))//
                                                .statements(List.of(//
                                                        JavaTryStatement.builder()//
                                                                .statements(List.of(//
                                                                        JavaExpressionStatement.builder()//
                                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                                        .target("chain")//
                                                                                        .invokes(List.of(//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("doFilter")//
                                                                                                        .arguments(List.of(//
                                                                                                                JavaVariableExpression.builder()//
                                                                                                                        .variable("req")//
                                                                                                                        .build(),//
                                                                                                                JavaVariableExpression.builder()//
                                                                                                                        .variable("res")//
                                                                                                                        .build()))//
                                                                                                        .build()))//
                                                                                        .build())//
                                                                                .build()))//
                                                                .catches(List.of(//
                                                                        JavaTryStatement.Catch.builder()//
                                                                                .exception("IllegalArgumentException")//
                                                                                .name("e")//
                                                                                .statements(List.of(//
                                                                                        JavaExpressionStatement.builder()//
                                                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                                                        .target("log")//
                                                                                                        .invokes(List.of(//
                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                        .method("error")//
                                                                                                                        .arguments(List.of(//
                                                                                                                                JavaValueExpression.builder()//
                                                                                                                                        .value("IllegalArgumentException: {}")//
                                                                                                                                        .type(String.class)//
                                                                                                                                        .build(),//
                                                                                                                                JavaMethodInvocationExpression.builder()//
                                                                                                                                        .target("e")//
                                                                                                                                        .invokes(List.of(//
                                                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                                                        .method("getMessage")//
                                                                                                                                                        .build()))//
                                                                                                                                        .build()))//
                                                                                                                        .build()))//
                                                                                                        .build())//
                                                                                                .build(),//
                                                                                        JavaExpressionStatement.builder()//
                                                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                                                        .target("this")//
                                                                                                        .invokes(List.of(//
                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                        .method("setErrorResponse")//
                                                                                                                        .arguments(List.of(//
                                                                                                                                JavaValueExpression.builder()//
                                                                                                                                        .value("org.springframework.http.HttpStatus.UNAUTHORIZED")//
                                                                                                                                        .type(HttpStatus.class)//
                                                                                                                                        .build(),//
                                                                                                                                JavaVariableExpression.builder()//
                                                                                                                                        .variable("req")//
                                                                                                                                        .build(),//
                                                                                                                                JavaVariableExpression.builder()//
                                                                                                                                        .variable("res")//
                                                                                                                                        .build(),//
                                                                                                                                JavaValueExpression.builder()//
                                                                                                                                        .value("An error occurred while fetching name from Token!")//
                                                                                                                                        .type(String.class)//
                                                                                                                                        .build()))
                                                                                                                        .build()))//
                                                                                                        .build())//
                                                                                                .build()))//
                                                                                .build(),//
                                                                        JavaTryStatement.Catch.builder()//
                                                                                .exception("io.jsonwebtoken.ExpiredJwtException")//
                                                                                .name("e")//
                                                                                .statements(List.of(//
                                                                                        JavaExpressionStatement.builder()//
                                                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                                                        .target("log")//
                                                                                                        .invokes(List.of(//
                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                        .method("error")//
                                                                                                                        .arguments(List.of(//
                                                                                                                                JavaValueExpression.builder()//
                                                                                                                                        .value("ExpiredJwtException: {}")//
                                                                                                                                        .type(String.class)//
                                                                                                                                        .build(),//
                                                                                                                                JavaMethodInvocationExpression.builder()//
                                                                                                                                        .target("e")//
                                                                                                                                        .invokes(List.of(//
                                                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                                                        .method("getMessage")//
                                                                                                                                                        .build()))//
                                                                                                                                        .build()))//
                                                                                                                        .build()))//
                                                                                                        .build())//
                                                                                                .build(),//
                                                                                        JavaExpressionStatement.builder()//
                                                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                                                        .target("this")//
                                                                                                        .invokes(List.of(//
                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                        .method("setErrorResponse")//
                                                                                                                        .arguments(List.of(//
                                                                                                                                JavaValueExpression.builder()//
                                                                                                                                        .value("org.springframework.http.HttpStatus.UNAUTHORIZED")//
                                                                                                                                        .type(HttpStatus.class)//
                                                                                                                                        .build(),//
                                                                                                                                JavaVariableExpression.builder()//
                                                                                                                                        .variable("req")//
                                                                                                                                        .build(),//
                                                                                                                                JavaVariableExpression.builder()//
                                                                                                                                        .variable("res")//
                                                                                                                                        .build(),//
                                                                                                                                JavaValueExpression.builder()//
                                                                                                                                        .value("The token has expired!")//
                                                                                                                                        .type(String.class)//
                                                                                                                                        .build()))
                                                                                                                        .build()))//
                                                                                                        .build())//
                                                                                                .build()))//
                                                                                .build(),//
                                                                        JavaTryStatement.Catch.builder()//
                                                                                .exception("io.jsonwebtoken.SignatureException")//
                                                                                .name("e")//
                                                                                .statements(List.of(//
                                                                                        JavaExpressionStatement.builder()//
                                                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                                                        .target("log")//
                                                                                                        .invokes(List.of(//
                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                        .method("error")//
                                                                                                                        .arguments(List.of(//
                                                                                                                                JavaValueExpression.builder()//
                                                                                                                                        .value("SignatureException: {}")//
                                                                                                                                        .type(String.class)//
                                                                                                                                        .build(),//
                                                                                                                                JavaMethodInvocationExpression.builder()//
                                                                                                                                        .target("e")//
                                                                                                                                        .invokes(List.of(//
                                                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                                                        .method("getMessage")//
                                                                                                                                                        .build()))//
                                                                                                                                        .build()))//
                                                                                                                        .build()))//
                                                                                                        .build())//
                                                                                                .build(),//
                                                                                        JavaExpressionStatement.builder()//
                                                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                                                        .target("this")//
                                                                                                        .invokes(List.of(//
                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                        .method("setErrorResponse")//
                                                                                                                        .arguments(List.of(//
                                                                                                                                JavaValueExpression.builder()//
                                                                                                                                        .value("org.springframework.http.HttpStatus.UNAUTHORIZED")//
                                                                                                                                        .type(HttpStatus.class)//
                                                                                                                                        .build(),//
                                                                                                                                JavaVariableExpression.builder()//
                                                                                                                                        .variable("req")//
                                                                                                                                        .build(),//
                                                                                                                                JavaVariableExpression.builder()//
                                                                                                                                        .variable("res")//
                                                                                                                                        .build(),//
                                                                                                                                JavaValueExpression.builder()//
                                                                                                                                        .value("Authentication Failed. Name or Password not valid!")//
                                                                                                                                        .type(String.class)//
                                                                                                                                        .build()))
                                                                                                                        .build()))//
                                                                                                        .build())//
                                                                                                .build()))//
                                                                                .build(),//
                                                                        JavaTryStatement.Catch.builder()//
                                                                                .exception("RuntimeException")//
                                                                                .name("e")//
                                                                                .statements(List.of(//
                                                                                        JavaExpressionStatement.builder()//
                                                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                                                        .target("log")//
                                                                                                        .invokes(List.of(//
                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                        .method("error")//
                                                                                                                        .arguments(List.of(//
                                                                                                                                JavaValueExpression.builder()//
                                                                                                                                        .value("RuntimeException: {}")//
                                                                                                                                        .type(String.class)//
                                                                                                                                        .build(),//
                                                                                                                                JavaMethodInvocationExpression.builder()//
                                                                                                                                        .target("e")//
                                                                                                                                        .invokes(List.of(//
                                                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                                                        .method("getMessage")//
                                                                                                                                                        .build()))//
                                                                                                                                        .build()))//
                                                                                                                        .build()))//
                                                                                                        .build())//
                                                                                                .build(),//
                                                                                        JavaExpressionStatement.builder()//
                                                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                                                        .target("this")//
                                                                                                        .invokes(List.of(//
                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                        .method("setErrorResponse")//
                                                                                                                        .arguments(List.of(//
                                                                                                                                JavaValueExpression.builder()//
                                                                                                                                        .value("org.springframework.http.HttpStatus.INTERNAL_SERVER_ERROR")//
                                                                                                                                        .type(HttpStatus.class)//
                                                                                                                                        .build(),//
                                                                                                                                JavaVariableExpression.builder()//
                                                                                                                                        .variable("req")//
                                                                                                                                        .build(),//
                                                                                                                                JavaVariableExpression.builder()//
                                                                                                                                        .variable("res")//
                                                                                                                                        .build(),//
                                                                                                                                JavaValueExpression.builder()//
                                                                                                                                        .value("Unexpected error!")//
                                                                                                                                        .type(String.class)//
                                                                                                                                        .build()))
                                                                                                                        .build()))//
                                                                                                        .build())//
                                                                                                .build()))//
                                                                                .build()))//
                                                                .build()))//
                                                .build(),//
                                        JavaMethodDeclaration.builder()//
                                                .name("setErrorResponse")//
                                                .returnType("void")//
                                                .modifiers(JavaModifier.builder()//
                                                        .type(JavaModifier.METHOD_MODIFIERS)//
                                                        .modifiers(Modifier.PRIVATE)//
                                                        .build())//
                                                .parameters(List.of(//
                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                .name("status")//
                                                                .type("org.springframework.http.HttpStatus")//
                                                                .build(),//
                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                .name("req")//
                                                                .type("javax.servlet.http.HttpServletRequest")//
                                                                .build(),//
                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                .name("res")//
                                                                .type("javax.servlet.http.HttpServletResponse")//
                                                                .build(),//
                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                .name("message")//
                                                                .type("String")//
                                                                .build()))//
                                                .statements(List.of(//
                                                        JavaExpressionStatement.builder()//
                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                        .target("res")//
                                                                        .invokes(List.of(//
                                                                                JavaMethodInvoke.builder()//
                                                                                        .method("setStatus")//
                                                                                        .arguments(List.of(//
                                                                                                JavaMethodInvocationExpression.builder()//
                                                                                                        .target("status")//
                                                                                                        .invokes(List.of(//
                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                        .method("value")//
                                                                                                                        .build()))//
                                                                                                        .build()))//
                                                                                        .build()))//
                                                                        .build())//
                                                                .build(),//
                                                        JavaExpressionStatement.builder()//
                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                        .target("res")//
                                                                        .invokes(List.of(//
                                                                                JavaMethodInvoke.builder()//
                                                                                        .method("setContentType")//
                                                                                        .arguments(List.of(//
                                                                                                JavaValueExpression.builder()//
                                                                                                        .value("application/json")//
                                                                                                        .type(String.class)//
                                                                                                        .build()))//
                                                                                        .build()))//
                                                                        .build())//
                                                                .build(),//
                                                        JavaDeclarationStatement.builder()//
                                                                .name("apiError")//
                                                                .type("website.smoothy.".concat(name.toLowerCase()).concat(".control.util.ApiError"))//
                                                                .initialized(true)//
                                                                .expression(JavaNewInstanceExpression.builder()//
                                                                        .name("website.smoothy.".concat(name.toLowerCase()).concat(".control.util.ApiError"))
                                                                        .arguments(List.of(//
                                                                                JavaVariableExpression.builder()//
                                                                                        .variable("status")//
                                                                                        .build(),//
                                                                                JavaMethodInvocationExpression.builder()//
                                                                                        .target("req")//
                                                                                        .invokes(List.of(//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("getRequestURI")//
                                                                                                        .build()))//
                                                                                        .build(),//
                                                                                JavaVariableExpression.builder()//
                                                                                        .variable("message")//
                                                                                        .build()))//
                                                                        .build())//
                                                                .build(),//
                                                        JavaTryStatement.builder()//
                                                                .statements(List.of(//
                                                                        JavaExpressionStatement.builder()//
                                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                                        .target("res")//
                                                                                        .invokes(List.of(//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("getWriter")//
                                                                                                        .build(),//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("write")//
                                                                                                        .arguments(List.of(//
                                                                                                                JavaMethodInvocationExpression.builder()//
                                                                                                                        .target("apiError")
                                                                                                                        .invokes(List.of(//
                                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                                        .method("convertToJson")//
                                                                                                                                        .build()))//
                                                                                                                        .build()))//
                                                                                                        .build()))//
                                                                                        .build())//
                                                                                .build()))//
                                                                .catches(List.of(//
                                                                        JavaTryStatement.Catch.builder()//
                                                                                .exception("java.io.IOException")//
                                                                                .name("e")//
                                                                                .statements(List.of(//
                                                                                        JavaExpressionStatement.builder()//
                                                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                                                        .target("e")//
                                                                                                        .invokes(List.of(//
                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                        .method("printStackTrace")//
                                                                                                                        .build()))//
                                                                                                        .build())//
                                                                                                .build()))//
                                                                                .build()))//
                                                                .build()))//
                                                .build()))//
                                .build()))//
                .build();
    }

}
