package solutions.thex.smoothy.generator.spring.main.src.java.security.filter;

import solutions.thex.smoothy.code.java.declaration.JavaFieldDeclaration;
import solutions.thex.smoothy.code.java.declaration.JavaMethodDeclaration;
import solutions.thex.smoothy.code.java.expression.*;
import solutions.thex.smoothy.code.java.expression.util.JavaMethodInvoke;
import solutions.thex.smoothy.code.java.source.JavaCompilationUnit;
import solutions.thex.smoothy.code.java.source.JavaTypeDeclaration;
import solutions.thex.smoothy.code.java.statement.JavaAssignStatement;
import solutions.thex.smoothy.code.java.statement.JavaControlStatement;
import solutions.thex.smoothy.code.java.statement.JavaDeclarationStatement;
import solutions.thex.smoothy.code.java.statement.JavaExpressionStatement;
import solutions.thex.smoothy.code.java.util.JavaAnnotation;
import solutions.thex.smoothy.code.java.util.JavaModifier;
import solutions.thex.smoothy.code.java.util.JavaOperand;
import solutions.thex.smoothy.code.java.util.JavaType;

import java.lang.reflect.Modifier;
import java.util.List;

public class JwtAuthenticationFilterGenerator {

    public static JavaCompilationUnit generate(String name) {
        return JavaCompilationUnit.builder()//
                .packageName("website.smoothy.".concat(name.toLowerCase()).concat(".security.filter"))//
                .name("JwtAuthenticationFilter")//
                .typeDeclarations(
                        List.of(//
                                JavaTypeDeclaration.builder()//
                                        .type(JavaType.CLASS)//
                                        .name("JwtAuthenticationFilter")//
                                        .modifiers(JavaModifier.builder()//
                                                .type(JavaModifier.TYPE_MODIFIERS)//
                                                .modifiers(Modifier.PUBLIC)//
                                                .build())//
                                        .extendedClassName("org.springframework.web.filter.OncePerRequestFilter")//
                                        .annotations(List.of(//
                                                JavaAnnotation.builder()//
                                                        .name("org.springframework.stereotype.Service")//
                                                        .build()))//
                                        .fieldDeclarations(List.of(//
                                                JavaFieldDeclaration.builder()//
                                                        .name("HEADER_STRING")//
                                                        .type("String")//
                                                        .modifiers(JavaModifier.builder()//
                                                                .type(JavaModifier.FIELD_MODIFIERS)//
                                                                .modifiers(Modifier.PUBLIC)//
                                                                .build())//
                                                        .annotations(List.of(//
                                                                JavaAnnotation.builder()//
                                                                        .name("org.springframework.beans.factory.annotation.Value")//
                                                                        .attributes(List.of(//
                                                                                JavaAnnotation.Attribute.builder()//
                                                                                        .type(String.class)//
                                                                                        .values(List.of("${jwt.signing.key}"))//
                                                                                        .build()))//
                                                                        .build()))//
                                                        .build(),//
                                                JavaFieldDeclaration.builder()//
                                                        .name("TOKEN_PREFIX")//
                                                        .type("String")//
                                                        .modifiers(JavaModifier.builder()//
                                                                .type(JavaModifier.FIELD_MODIFIERS)//
                                                                .modifiers(Modifier.PUBLIC)//
                                                                .build())//
                                                        .annotations(List.of(//
                                                                JavaAnnotation.builder()//
                                                                        .name("org.springframework.beans.factory.annotation.Value")//
                                                                        .attributes(List.of(//
                                                                                JavaAnnotation.Attribute.builder()//
                                                                                        .type(String.class)//
                                                                                        .values(List.of("${jwt.token.prefix}"))//
                                                                                        .build()))//
                                                                        .build()))//
                                                        .build(),//
                                                JavaFieldDeclaration.builder()//
                                                        .name("userDetailsService")//
                                                        .type("org.springframework.security.core.userdetails.UserDetailsService")//
                                                        .modifiers(JavaModifier.builder()//
                                                                .type(JavaModifier.FIELD_MODIFIERS)//
                                                                .modifiers(Modifier.PRIVATE)//
                                                                .build())//
                                                        .annotations(List.of(//
                                                                JavaAnnotation.builder()//
                                                                        .name("javax.annotation.Resource")//
                                                                        .attributes(List.of(//
                                                                                JavaAnnotation.Attribute.builder()//
                                                                                        .name("name")//
                                                                                        .type(String.class)//
                                                                                        .values(List.of("userDetailsService"))//
                                                                                        .build()))//
                                                                        .build()))//
                                                        .build(),//
                                                JavaFieldDeclaration.builder()//
                                                        .name("jwtTokenUtil")//
                                                        .type("website.smoothy." + name.toLowerCase() + ".security.jwt.Jwt")//
                                                        .modifiers(JavaModifier.builder()//
                                                                .type(JavaModifier.FIELD_MODIFIERS)//
                                                                .modifiers(Modifier.PRIVATE)//
                                                                .build())//
                                                        .build()))//
                                        .methodDeclarations(List.of(//
                                                JavaMethodDeclaration.builder()//
                                                        .name("JwtAuthenticationFilter")//
                                                        .returnType("")//
                                                        .modifiers(JavaModifier.builder()//
                                                                .type(JavaModifier.METHOD_MODIFIERS)//
                                                                .modifiers(Modifier.PUBLIC)//
                                                                .build())//
                                                        .annotations(List.of(//
                                                                JavaAnnotation.builder()//
                                                                        .name("org.springframework.beans.factory.annotation.Autowired")//
                                                                        .build()))//
                                                        .parameters(List.of(//
                                                                JavaMethodDeclaration.Parameter.builder()//
                                                                        .name("jwtTokenUtil")//
                                                                        .type("website.smoothy." + name.toLowerCase() + ".security.jwt.Jwt")//
                                                                        .build()))//
                                                        .build(),//
                                                JavaMethodDeclaration.builder()//
                                                        .name("doFilterInternal")//
                                                        .returnType("void")//
                                                        .modifiers(JavaModifier.builder()//
                                                                .type(JavaModifier.METHOD_MODIFIERS)//
                                                                .modifiers(Modifier.PROTECTED)//
                                                                .build())//
                                                        .annotations(List.of(//
                                                                JavaAnnotation.builder()//
                                                                        .name("Override")//
                                                                        .build()))//
                                                        .parameters(List.of(//
                                                                JavaMethodDeclaration.Parameter.builder()//
                                                                        .name("req")//
                                                                        .type("javax.servlet.http.HttpServletRequest")//
                                                                        .build(),//
                                                                JavaMethodDeclaration.Parameter.builder()//
                                                                        .name("res")//
                                                                        .type("javax.servlet.http.HttpServletResponse")//
                                                                        .build(),//
                                                                JavaMethodDeclaration.Parameter.builder()//
                                                                        .name("chain")//
                                                                        .type("javax.servlet.FilterChain")//
                                                                        .build()))//
                                                        .isThrows(true)//
                                                        .exceptions(List.of("java.io.IOException", "javax.servlet.ServletException"))//
                                                        .statements(List.of(//
                                                                JavaDeclarationStatement.builder()//
                                                                        .name("header")//
                                                                        .type("String")//
                                                                        .initialized(true)//
                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                .target("req")//
                                                                                .invokes(List.of(//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("getHeader")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaVariableExpression.builder()//
                                                                                                                .variable("HEADER_STRING")//
                                                                                                                .build()))//
                                                                                                .build()))//
                                                                                .build())//
                                                                        .build(),//
                                                                JavaDeclarationStatement.builder()//
                                                                        .name("name")//
                                                                        .type("String")//
                                                                        .initialized(true)//
                                                                        .expression(JavaValueExpression.builder()//
                                                                                .value("null")//
                                                                                .type(null)//
                                                                                .build())//
                                                                        .build(),//
                                                                JavaDeclarationStatement.builder()//
                                                                        .name("authToken")//
                                                                        .type("String")//
                                                                        .initialized(true)//
                                                                        .expression(JavaValueExpression.builder()//
                                                                                .value("null")//
                                                                                .type(null)//
                                                                                .build())//
                                                                        .build(),//
                                                                JavaControlStatement.builder()//
                                                                        .ifs(List.of(//
                                                                                JavaControlStatement.If.builder()//
                                                                                        .condition(JavaBraceletExpression.builder()//
                                                                                                .bracelet(false)//
                                                                                                .expressions(List.of(
                                                                                                        JavaVariableExpression.builder()//
                                                                                                                .variable("header")//
                                                                                                                .operand(JavaOperand.NOT_EQUAL)//
                                                                                                                .build(),//
                                                                                                        JavaValueExpression.builder()//
                                                                                                                .value("null")//
                                                                                                                .type(null)//
                                                                                                                .operand(JavaOperand.AND)//
                                                                                                                .build(),
                                                                                                        JavaMethodInvocationExpression.builder()//
                                                                                                                .target("header")//
                                                                                                                .invokes(List.of(//
                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                .method("startsWith")
                                                                                                                                .arguments(List.of(
                                                                                                                                        JavaVariableExpression.builder()//
                                                                                                                                                .variable("TOKEN_PREFIX")//
                                                                                                                                                .build()))//
                                                                                                                                .build()))//
                                                                                                                .build()))//
                                                                                                .build())//
                                                                                        .statements(List.of(
                                                                                                JavaAssignStatement.builder()//
                                                                                                        .variable("authToken")//
                                                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                                                .target("header")//
                                                                                                                .invokes(List.of(//
                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                .method("replace")//
                                                                                                                                .arguments(List.of(
                                                                                                                                        JavaVariableExpression.builder()//
                                                                                                                                                .variable("TOKEN_PREFIX")//
                                                                                                                                                .build(),//
                                                                                                                                        JavaValueExpression.builder()//
                                                                                                                                                .value("")//
                                                                                                                                                .type(String.class)//
                                                                                                                                                .build()))//
                                                                                                                                .build()))//
                                                                                                                .build())//
                                                                                                        .build(),//
                                                                                                JavaAssignStatement.builder()//
                                                                                                        .variable("name")//
                                                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                                                .target("jwtTokenUtil")//
                                                                                                                .invokes(List.of(//
                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                .method("getUsernameFromToken")//
                                                                                                                                .arguments(List.of(
                                                                                                                                        JavaVariableExpression.builder()//
                                                                                                                                                .variable("authToken")//
                                                                                                                                                .build()))//
                                                                                                                                .build()))//
                                                                                                                .build())//
                                                                                                        .build()))//
                                                                                        .build()))//
                                                                        .build(),//
                                                                JavaControlStatement.builder()//
                                                                        .ifs(List.of(//
                                                                                JavaControlStatement.If.builder()//
                                                                                        .condition(JavaBraceletExpression.builder()//
                                                                                                .bracelet(false)//
                                                                                                .expressions(List.of(
                                                                                                        JavaVariableExpression.builder()//
                                                                                                                .variable("name")//
                                                                                                                .operand(JavaOperand.NOT_EQUAL)//
                                                                                                                .build(),//
                                                                                                        JavaValueExpression.builder()//
                                                                                                                .value("null")//
                                                                                                                .type(null)//
                                                                                                                .operand(JavaOperand.AND)//
                                                                                                                .build(),
                                                                                                        JavaMethodInvocationExpression.builder()//
                                                                                                                .target("org.springframework.security.core.context.SecurityContextHolder")//
                                                                                                                .invokes(List.of(//
                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                .method("getContext")
                                                                                                                                .build(),//
                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                .method("getAuthentication")
                                                                                                                                .build()))//
                                                                                                                .operand(JavaOperand.EQUAL)//
                                                                                                                .build(),//
                                                                                                        JavaValueExpression.builder()//
                                                                                                                .value("null")//
                                                                                                                .type(null)//
                                                                                                                .build()))//
                                                                                                .build())//
                                                                                        .statements(List.of(
                                                                                                JavaDeclarationStatement.builder()//
                                                                                                        .type("org.springframework.security.core.userdetails.UserDetails")//
                                                                                                        .name("userDetails")//
                                                                                                        .initialized(true)//
                                                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                                                .target("userDetailsService")//
                                                                                                                .invokes(List.of(//
                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                .method("loadUserByUsername")//
                                                                                                                                .arguments(List.of(
                                                                                                                                        JavaVariableExpression.builder()//
                                                                                                                                                .variable("name")//
                                                                                                                                                .build()))//
                                                                                                                                .build()))//
                                                                                                                .build())//
                                                                                                        .build(),//
                                                                                                JavaControlStatement.builder()//
                                                                                                        .ifs(List.of(//
                                                                                                                JavaControlStatement.If.builder()//
                                                                                                                        .condition(JavaBraceletExpression.builder()//
                                                                                                                                .bracelet(false)//
                                                                                                                                .expressions(List.of(//
                                                                                                                                        JavaMethodInvocationExpression.builder()//
                                                                                                                                                .target("jwtTokenUtil")//
                                                                                                                                                .invokes(List.of(//
                                                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                                                .method("validateToken")//
                                                                                                                                                                .arguments(List.of(
                                                                                                                                                                        JavaVariableExpression.builder()//
                                                                                                                                                                                .variable("authToken")//
                                                                                                                                                                                .build(),//
                                                                                                                                                                        JavaVariableExpression.builder()//
                                                                                                                                                                                .variable("userDetails")//
                                                                                                                                                                                .build()))//
                                                                                                                                                                .build()))//
                                                                                                                                                .build()))//
                                                                                                                                .build())//
                                                                                                                        .statements(List.of(
                                                                                                                                JavaDeclarationStatement.builder()//
                                                                                                                                        .type("org.springframework.security.authentication.UsernamePasswordAuthenticationToken")//
                                                                                                                                        .name("authentication")//
                                                                                                                                        .initialized(true)//
                                                                                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                                                                                .target("jwtTokenUtil")//
                                                                                                                                                .invokes(List.of(//
                                                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                                                .method("getAuthenticationToken")//
                                                                                                                                                                .arguments(List.of(//
                                                                                                                                                                        JavaVariableExpression.builder()//
                                                                                                                                                                                .variable("authToken")//
                                                                                                                                                                                .build(),//
                                                                                                                                                                        JavaMethodInvocationExpression.builder()//
                                                                                                                                                                                .target("org.springframework.security.core.context.SecurityContextHolder")//
                                                                                                                                                                                .invokes(List.of(//
                                                                                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                                                                                .method("getContext")//
                                                                                                                                                                                                .build(),//
                                                                                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                                                                                .method("getAuthentication")//
                                                                                                                                                                                                .build()))//
                                                                                                                                                                                .build(),//
                                                                                                                                                                        JavaVariableExpression.builder()//
                                                                                                                                                                                .variable("userDetails")//
                                                                                                                                                                                .build()))//
                                                                                                                                                                .build()))//
                                                                                                                                                .build())//
                                                                                                                                        .build(),//
                                                                                                                                JavaExpressionStatement.builder()//
                                                                                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                                                                                .target("authentication")//
                                                                                                                                                .invokes(List.of(//
                                                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                                                .method("setDetails")//
                                                                                                                                                                .arguments(List.of(//
                                                                                                                                                                        JavaNewInstanceExpression.builder()//
                                                                                                                                                                                .name("org.springframework.security.web.authentication.WebAuthenticationDetailsSource")//
                                                                                                                                                                                .invokes(List.of(//
                                                                                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                                                                                .method("buildDetails")//
                                                                                                                                                                                                .arguments(List.of(//
                                                                                                                                                                                                        JavaVariableExpression.builder()//
                                                                                                                                                                                                                .variable("req")
                                                                                                                                                                                                                .build()))//
                                                                                                                                                                                                .build()))//
                                                                                                                                                                                .build()))//
                                                                                                                                                                .build()))//
                                                                                                                                                .build())//
                                                                                                                                        .build(),//
                                                                                                                                JavaExpressionStatement.builder()//
                                                                                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                                                                                .target("org.springframework.security.core.context.SecurityContextHolder")//
                                                                                                                                                .invokes(List.of(//
                                                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                                                .method("getContext")//
                                                                                                                                                                .build(),//
                                                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                                                .method("setAuthentication")//
                                                                                                                                                                .arguments(List.of(JavaVariableExpression.builder()//
                                                                                                                                                                        .variable("authentication")//
                                                                                                                                                                        .build()))//
                                                                                                                                                                .build()))//
                                                                                                                                                .build())//
                                                                                                                                        .build()))//
                                                                                                                        .build()))//
                                                                                                        .build()))//
                                                                                        .build()))//
                                                                        .build(),//
                                                                JavaExpressionStatement.builder()//
                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                .target("chain")//
                                                                                .invokes(List.of(//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("doFilter")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaVariableExpression.builder()//
                                                                                                                .variable("req")
                                                                                                                .build(),//
                                                                                                        JavaVariableExpression.builder()//
                                                                                                                .variable("res")
                                                                                                                .build()))//
                                                                                                .build()))//
                                                                                .build())//
                                                                        .build()))//
                                                        .build()))//
                                        .build()))//
                .build();
    }

}
