package solutions.thex.smoothy.generator.spring.main.src.java.control.util;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.SerializationFeature;
import solutions.thex.smoothy.code.java.declaration.JavaFieldDeclaration;
import solutions.thex.smoothy.code.java.declaration.JavaMethodDeclaration;
import solutions.thex.smoothy.code.java.expression.*;
import solutions.thex.smoothy.code.java.expression.util.JavaMethodInvoke;
import solutions.thex.smoothy.code.java.source.JavaCompilationUnit;
import solutions.thex.smoothy.code.java.source.JavaTypeDeclaration;
import solutions.thex.smoothy.code.java.statement.*;
import solutions.thex.smoothy.code.java.util.JavaAnnotation;
import solutions.thex.smoothy.code.java.util.JavaModifier;
import solutions.thex.smoothy.code.java.util.JavaOperand;
import solutions.thex.smoothy.code.java.util.JavaType;

import java.lang.reflect.Modifier;
import java.util.List;

public class ApiErrorGenerator {

    public static JavaCompilationUnit generate(String name) {
        return JavaCompilationUnit.builder()//
                .packageName("website.smoothy.".concat(name.toLowerCase()).concat(".control.util"))//
                .name("ApiError")//
                .typeDeclarations(List.of(//
                        JavaTypeDeclaration.builder()//
                                .type(JavaType.CLASS)//
                                .name("ApiError")//
                                .modifiers(JavaModifier.builder()//
                                        .type(JavaModifier.TYPE_MODIFIERS)//
                                        .modifiers(Modifier.PUBLIC)//
                                        .build())//
                                .annotations(List.of(//
                                        JavaAnnotation.builder()//
                                                .name("lombok.Getter")//
                                                .build(),//
                                        JavaAnnotation.builder()//
                                                .name("lombok.Setter")//
                                                .build(),//
                                        JavaAnnotation.builder()//
                                                .name("com.fasterxml.jackson.annotation.JsonPropertyOrder")//
                                                .attributes(List.of(//
                                                        JavaAnnotation.Attribute.builder()//
                                                                .type(String.class)//
                                                                .values(List.of("timestamp", "status", "error", "message", "path"))//
                                                                .build()))//
                                                .build()))//
                                .fieldDeclarations(List.of(//
                                        JavaFieldDeclaration.builder()//
                                                .name("timestamp")//
                                                .type("java.time.ZonedDateTime")//
                                                .modifiers(JavaModifier.builder()//
                                                        .type(JavaModifier.FIELD_MODIFIERS)//
                                                        .modifiers(Modifier.PRIVATE)//
                                                        .build())//
                                                .annotations(List.of(//
                                                        JavaAnnotation.builder()//
                                                                .name("com.fasterxml.jackson.databind.annotation.JsonSerialize")//
                                                                .attributes(List.of(//
                                                                        JavaAnnotation.Attribute.builder()//
                                                                                .type(Class.class)//
                                                                                .name("using")//
                                                                                .values(List.of("com.fasterxml.jackson.datatype.jsr310.ser.ZonedDateTimeSerializer"))//
                                                                                .build()))//
                                                                .build(),//
                                                        JavaAnnotation.builder()//
                                                                .name("com.fasterxml.jackson.annotation.JsonFormat")//
                                                                .attributes(List.of(//
                                                                        JavaAnnotation.Attribute.builder()//
                                                                                .type(JsonFormat.Shape.class)//
                                                                                .name("shape")//
                                                                                .values(List.of("com.fasterxml.jackson.annotation.JsonFormat.Shape.STRING"))//
                                                                                .build(),//
                                                                        JavaAnnotation.Attribute.builder()//
                                                                                .type(String.class)//
                                                                                .name("pattern")//
                                                                                .values(List.of("yyyy-MM-dd'T'HH:mm:ss.SSSZ"))//
                                                                                .build()))//
                                                                .build()))//
                                                .build(),//
                                        JavaFieldDeclaration.builder()//
                                                .name("status")//
                                                .type("int")//
                                                .modifiers(JavaModifier.builder()//
                                                        .type(JavaModifier.FIELD_MODIFIERS)//
                                                        .modifiers(Modifier.PRIVATE)//
                                                        .build())//
                                                .build(),//
                                        JavaFieldDeclaration.builder()//
                                                .name("error")//
                                                .type("String")//
                                                .modifiers(JavaModifier.builder()//
                                                        .type(JavaModifier.FIELD_MODIFIERS)//
                                                        .modifiers(Modifier.PRIVATE)//
                                                        .build())//
                                                .build(),//
                                        JavaFieldDeclaration.builder()//
                                                .name("message")//
                                                .type("String")//
                                                .modifiers(JavaModifier.builder()//
                                                        .type(JavaModifier.FIELD_MODIFIERS)//
                                                        .modifiers(Modifier.PRIVATE)//
                                                        .build())//
                                                .build(),//
                                        JavaFieldDeclaration.builder()//
                                                .name("path")//
                                                .type("String")//
                                                .modifiers(JavaModifier.builder()//
                                                        .type(JavaModifier.FIELD_MODIFIERS)//
                                                        .modifiers(Modifier.PRIVATE)//
                                                        .build())//
                                                .build()))//
                                .methodDeclarations(List.of(//
                                        JavaMethodDeclaration.builder()//
                                                .name("ApiError")//
                                                .returnType("")//
                                                .modifiers(JavaModifier.builder()//
                                                        .type(JavaModifier.METHOD_MODIFIERS)//
                                                        .modifiers(Modifier.PUBLIC)//
                                                        .build())//
                                                .statements(List.of(//
                                                        JavaAssignStatement.builder()//
                                                                .variable("this.timestamp")//
                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                        .target("java.time.ZonedDateTime")
                                                                        .invokes(List.of(//
                                                                                JavaMethodInvoke.builder()//
                                                                                        .method("now")//
                                                                                        .build()))
                                                                        .build())//
                                                                .build()))//
                                                .build(),//
                                        JavaMethodDeclaration.builder()//
                                                .name("ApiError")//
                                                .returnType("")//
                                                .modifiers(JavaModifier.builder()//
                                                        .type(JavaModifier.METHOD_MODIFIERS)//
                                                        .modifiers(Modifier.PUBLIC)//
                                                        .build())//
                                                .parameters(List.of(//
                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                .type("org.springframework.http.HttpStatus")//
                                                                .name("status")//
                                                                .build(),//
                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                .type("String")//
                                                                .name("path")//
                                                                .build()))//
                                                .statements(List.of(//
                                                        JavaExpressionStatement.builder()//
                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                        .target("this")//
                                                                        .build())//
                                                                .build(),//
                                                        JavaAssignStatement.builder()//
                                                                .variable("this.status")//
                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                        .target("status")
                                                                        .invokes(List.of(//
                                                                                JavaMethodInvoke.builder()//
                                                                                        .method("value")//
                                                                                        .build()))
                                                                        .build())//
                                                                .build(),//
                                                        JavaAssignStatement.builder()//
                                                                .variable("this.error")//
                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                        .target("status")
                                                                        .invokes(List.of(//
                                                                                JavaMethodInvoke.builder()//
                                                                                        .method("getReasonPhrase")//
                                                                                        .build()))
                                                                        .build())//
                                                                .build(),//
                                                        JavaAssignStatement.builder()//
                                                                .variable("this.message")//
                                                                .expression(JavaValueExpression.builder()//
                                                                        .type(String.class)//
                                                                        .value("Unexpected error")
                                                                        .build())//
                                                                .build(),//
                                                        JavaAssignStatement.builder()//
                                                                .variable("this.path")//
                                                                .expression(JavaVariableExpression.builder()//
                                                                        .variable("path")//
                                                                        .build())//
                                                                .build()))//
                                                .build(),//
                                        JavaMethodDeclaration.builder()//
                                                .name("ApiError")//
                                                .returnType("")//
                                                .modifiers(JavaModifier.builder()//
                                                        .type(JavaModifier.METHOD_MODIFIERS)//
                                                        .modifiers(Modifier.PUBLIC)//
                                                        .build())//
                                                .parameters(List.of(//
                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                .type("org.springframework.http.HttpStatus")//
                                                                .name("status")//
                                                                .build(),//
                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                .type("String")//
                                                                .name("path")//
                                                                .build(),//
                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                .type("String")//
                                                                .name("message")//
                                                                .build()))//
                                                .statements(List.of(//
                                                        JavaExpressionStatement.builder()//
                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                        .target("this")//
                                                                        .build())//
                                                                .build(),//
                                                        JavaAssignStatement.builder()//
                                                                .variable("this.status")//
                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                        .target("status")
                                                                        .invokes(List.of(//
                                                                                JavaMethodInvoke.builder()//
                                                                                        .method("value")//
                                                                                        .build()))
                                                                        .build())//
                                                                .build(),//
                                                        JavaAssignStatement.builder()//
                                                                .variable("this.error")//
                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                        .target("status")
                                                                        .invokes(List.of(//
                                                                                JavaMethodInvoke.builder()//
                                                                                        .method("getReasonPhrase")//
                                                                                        .build()))
                                                                        .build())//
                                                                .build(),//
                                                        JavaAssignStatement.builder()//
                                                                .variable("this.message")//
                                                                .expression(JavaVariableExpression.builder()//
                                                                        .variable("message")//
                                                                        .build())//
                                                                .build(),//
                                                        JavaAssignStatement.builder()//
                                                                .variable("this.path")//
                                                                .expression(JavaVariableExpression.builder()//
                                                                        .variable("path")//
                                                                        .build())//
                                                                .build()))//
                                                .build(),//
                                        JavaMethodDeclaration.builder()//
                                                .name("convertToJson")//
                                                .returnType("String")//
                                                .modifiers(JavaModifier.builder()//
                                                        .type(JavaModifier.METHOD_MODIFIERS)//
                                                        .modifiers(Modifier.PUBLIC)//
                                                        .build())//
                                                .isThrows(true)//
                                                .exceptions(List.of("com.fasterxml.jackson.core.JsonProcessingException"))//
                                                .statements(List.of(//
                                                        JavaControlStatement.builder()//
                                                                .ifs(List.of(//
                                                                        JavaControlStatement.If.builder()//
                                                                                .condition(JavaBraceletExpression.builder()//
                                                                                        .bracelet(false)//
                                                                                        .expressions(List.of(//
                                                                                                JavaVariableExpression.builder()//
                                                                                                        .variable("this")
                                                                                                        .operand(JavaOperand.EQUAL)//
                                                                                                        .build(),//
                                                                                                JavaValueExpression.builder()//
                                                                                                        .type(null)//
                                                                                                        .value("null")//
                                                                                                        .build()))//
                                                                                        .build())//
                                                                                .statements(List.of(//
                                                                                        JavaReturnStatement.builder()//
                                                                                                .expression(JavaValueExpression.builder()//
                                                                                                        .type(null)//
                                                                                                        .value("null")//
                                                                                                        .build())//
                                                                                                .build()))//
                                                                                .build()))//
                                                                .build(),//
                                                        JavaDeclarationStatement.builder()//
                                                                .type("com.fasterxml.jackson.databind.ObjectMapper")//
                                                                .name("mapper")//
                                                                .initialized(true)//
                                                                .expression(JavaNewInstanceExpression.builder()//
                                                                        .name("com.fasterxml.jackson.databind.ObjectMapper")//
                                                                        .build())//
                                                                .build(),//
                                                        JavaExpressionStatement.builder()//
                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                        .target("mapper")//
                                                                        .invokes(List.of(//
                                                                                JavaMethodInvoke.builder()//
                                                                                        .method("registerModule")
                                                                                        .arguments(List.of(//
                                                                                                JavaNewInstanceExpression.builder()//
                                                                                                        .name("com.fasterxml.jackson.datatype.jsr310.JavaTimeModule")//
                                                                                                        .build()))//
                                                                                        .build()))//
                                                                        .build())//
                                                                .build(),//
                                                        JavaExpressionStatement.builder()//
                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                        .target("mapper")//
                                                                        .invokes(List.of(//
                                                                                JavaMethodInvoke.builder()//
                                                                                        .method("disable")
                                                                                        .arguments(List.of(//
                                                                                                JavaValueExpression.builder()//
                                                                                                        .value("com.fasterxml.jackson.databind.SerializationFeature.WRITE_DATES_AS_TIMESTAMPS")//
                                                                                                        .type(SerializationFeature.class)//
                                                                                                        .build()))//
                                                                                        .build()))//
                                                                        .build())//
                                                                .build(),//
                                                        JavaReturnStatement.builder()//
                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                        .target("mapper")//
                                                                        .invokes(List.of(//
                                                                                JavaMethodInvoke.builder()//
                                                                                        .method("writeValueAsString")//
                                                                                        .arguments(List.of(//
                                                                                                JavaVariableExpression.builder()//
                                                                                                        .variable("this")//
                                                                                                        .build()))//
                                                                                        .build()))//
                                                                        .build())//
                                                                .build()))//
                                                .build()))//
                                .build()))//
                .build();
    }

}
