package solutions.thex.smoothy.generator.spring.main.src.java.security;

import org.springframework.security.config.http.SessionCreationPolicy;
import solutions.thex.smoothy.code.java.declaration.JavaFieldDeclaration;
import solutions.thex.smoothy.code.java.declaration.JavaMethodDeclaration;
import solutions.thex.smoothy.code.java.expression.*;
import solutions.thex.smoothy.code.java.expression.util.JavaMethodInvoke;
import solutions.thex.smoothy.code.java.source.JavaCompilationUnit;
import solutions.thex.smoothy.code.java.source.JavaTypeDeclaration;
import solutions.thex.smoothy.code.java.statement.JavaAssignStatement;
import solutions.thex.smoothy.code.java.statement.JavaExpressionStatement;
import solutions.thex.smoothy.code.java.statement.JavaReturnStatement;
import solutions.thex.smoothy.code.java.util.JavaAnnotation;
import solutions.thex.smoothy.code.java.util.JavaModifier;
import solutions.thex.smoothy.code.java.util.JavaOperand;
import solutions.thex.smoothy.code.java.util.JavaType;

import javax.servlet.http.HttpServletResponse;
import java.lang.reflect.Modifier;
import java.util.List;

public class SecurityConfigGenerator {

    public static List<JavaCompilationUnit> generate(String name) {
        return List.of(//
                JavaCompilationUnit.builder()//
                        .packageName("website.smoothy.".concat(name.toLowerCase()).concat(".security"))//
                        .name("SecurityConfig")//
                        .typeDeclarations(
                                List.of(//
                                        JavaTypeDeclaration.builder()//
                                                .type(JavaType.CLASS)//
                                                .name("SecurityConfig")//
                                                .modifiers(JavaModifier.builder()//
                                                        .type(JavaModifier.TYPE_MODIFIERS)//
                                                        .modifiers(Modifier.PUBLIC)//
                                                        .build())//
                                                .extendedClassName("org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter")//
                                                .annotations(List.of(//
                                                        JavaAnnotation.builder()//
                                                                .name("org.springframework.context.annotation.Configuration")//
                                                                .build(),//
                                                        JavaAnnotation.builder()//
                                                                .name("org.springframework.security.config.annotation.web.configuration.EnableWebSecurity")//
                                                                .build(),//
                                                        JavaAnnotation.builder()//
                                                                .name("org.springframework.security.config.annotation.method.configuration.EnableGlobalMethodSecurity")//
                                                                .attributes(List.of(//
                                                                        JavaAnnotation.Attribute.builder()//
                                                                                .name("prePostEnabled")//
                                                                                .type(boolean.class)//
                                                                                .values(List.of("true"))//
                                                                                .build()))//
                                                                .build()))//
                                                .fieldDeclarations(List.of(//
                                                        JavaFieldDeclaration.builder()//
                                                                .name("userDetailsService")//
                                                                .type("org.springframework.security.core.userdetails.UserDetailsService")//
                                                                .modifiers(JavaModifier.builder()//
                                                                        .type(JavaModifier.FIELD_MODIFIERS)//
                                                                        .modifiers(Modifier.PRIVATE)//
                                                                        .build())//
                                                                .initialized(false)//
                                                                .annotations(List.of(//
                                                                        JavaAnnotation.builder()//
                                                                                .name("javax.annotation.Resource")//
                                                                                .attributes(List.of(//
                                                                                        JavaAnnotation.Attribute.builder()//
                                                                                                .name("name")//
                                                                                                .type(String.class)//
                                                                                                .values(List.of("userDetailsService"))//
                                                                                                .build()))//
                                                                                .build()))//
                                                                .build(),//
                                                        JavaFieldDeclaration.builder()//
                                                                .name("unauthorizedEntryPoint")//
                                                                .type("UnauthorizedEntryPoint")//
                                                                .modifiers(JavaModifier.builder()//
                                                                        .type(JavaModifier.FIELD_MODIFIERS)//
                                                                        .modifiers(Modifier.PRIVATE | Modifier.FINAL)//
                                                                        .build())//
                                                                .initialized(false)//
                                                                .build(),//
                                                        JavaFieldDeclaration.builder()//
                                                                .name("jwtAuthenticationFilter")//
                                                                .type("website.smoothy.".concat(name.toLowerCase()).concat(".security.jwt.JwtAuthenticationFilter"))//
                                                                .modifiers(JavaModifier.builder()//
                                                                        .type(JavaModifier.FIELD_MODIFIERS)//
                                                                        .modifiers(Modifier.PRIVATE | Modifier.FINAL)//
                                                                        .build())//
                                                                .initialized(false)//
                                                                .build()))//
                                                .methodDeclarations(List.of(//
                                                        JavaMethodDeclaration.builder()//
                                                                .name("SecurityConfig")//
                                                                .returnType("")//
                                                                .modifiers(JavaModifier.builder()//
                                                                        .type(JavaModifier.METHOD_MODIFIERS)//
                                                                        .modifiers(Modifier.PUBLIC)//
                                                                        .build())//
                                                                .annotations(List.of(//
                                                                        JavaAnnotation.builder()//
                                                                                .name("org.springframework.beans.factory.annotation.Autowired")//
                                                                                .build()))//
                                                                .parameters(List.of(//
                                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                                .name("unauthorizedEntryPoint")//
                                                                                .type("UnauthorizedEntryPoint")//
                                                                                .build(),//
                                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                                .name("jwtAuthenticationFilter")//
                                                                                .type("website.smoothy.".concat(name.toLowerCase()).concat(".security.jwt.JwtAuthenticationFilter"))//
                                                                                .build()))//
                                                                .statements(List.of(//
                                                                        JavaAssignStatement.builder()//
                                                                                .variable("this.unauthorizedEntryPoint")//
                                                                                .expression(JavaVariableExpression.builder()//
                                                                                        .variable("unauthorizedEntryPoint")//
                                                                                        .build())//
                                                                                .build(),//
                                                                        JavaAssignStatement.builder()//
                                                                                .variable("this.jwtAuthenticationFilter")//
                                                                                .expression(JavaVariableExpression.builder()//
                                                                                        .variable("jwtAuthenticationFilter")//
                                                                                        .build())//
                                                                                .build()))//
                                                                .build(),//
                                                        JavaMethodDeclaration.builder()//
                                                                .name("configure")//
                                                                .returnType("void")//
                                                                .modifiers(JavaModifier.builder()//
                                                                        .type(JavaModifier.METHOD_MODIFIERS)//
                                                                        .modifiers(Modifier.PUBLIC)//
                                                                        .build())//
                                                                .isThrows(true)//
                                                                .exceptions(List.of(//
                                                                        "Exception"))//
                                                                .annotations(List.of(//
                                                                        JavaAnnotation.builder()//
                                                                                .name("Override")//
                                                                                .build()))//
                                                                .parameters(List.of(//
                                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                                .name("auth")//
                                                                                .type("org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder")//
                                                                                .build()))//
                                                                .statements(List.of(//
                                                                        JavaExpressionStatement.builder()
                                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                                        .target("auth")//
                                                                                        .invokes(List.of(//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("userDetailsService")//
                                                                                                        .arguments(List.of(//
                                                                                                                JavaVariableExpression.builder()//
                                                                                                                        .variable("userDetailsService")
                                                                                                                        .build()))//
                                                                                                        .build(),//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("passwordEncoder")//
                                                                                                        .arguments(List.of(//
                                                                                                                JavaMethodInvocationExpression.builder()//
                                                                                                                        .target("this")//
                                                                                                                        .invokes(List.of(//
                                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                                        .method("encoder")//
                                                                                                                                        .build()))//
                                                                                                                        .build()))//
                                                                                                        .build()))//
                                                                                        .build())//
                                                                                .build()))//
                                                                .build(),//
                                                        JavaMethodDeclaration.builder()//
                                                                .name("configure")//
                                                                .returnType("void")//
                                                                .modifiers(JavaModifier.builder()//
                                                                        .type(JavaModifier.METHOD_MODIFIERS)//
                                                                        .modifiers(Modifier.PROTECTED)//
                                                                        .build())//
                                                                .isThrows(true)//
                                                                .exceptions(List.of(//
                                                                        "Exception"))//
                                                                .annotations(List.of(//
                                                                        JavaAnnotation.builder()//
                                                                                .name("Override")//
                                                                                .build()))//
                                                                .parameters(List.of(//
                                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                                .name("http")//
                                                                                .type("org.springframework.security.config.annotation.web.builders.HttpSecurity")//
                                                                                .build()))//
                                                                .statements(List.of(//
                                                                        JavaExpressionStatement.builder()
                                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                                        .target("http")//
                                                                                        .invokes(List.of(//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("csrf")//
                                                                                                        .build(),//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("disable")//
                                                                                                        .build(),//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("authorizeRequests")//
                                                                                                        .build(),//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("antMatchers")//
                                                                                                        .arguments(List.of(//
                                                                                                                JavaValueExpression.builder()//
                                                                                                                        .value("/favicon.ico")//
                                                                                                                        .type(String.class)//
                                                                                                                        .build(),//
                                                                                                                JavaValueExpression.builder()//
                                                                                                                        .value("/error")//
                                                                                                                        .type(String.class)//
                                                                                                                        .build(),//
                                                                                                                JavaValueExpression.builder()//
                                                                                                                        .value("/authenticate")//
                                                                                                                        .type(String.class)//
                                                                                                                        .build(),//
                                                                                                                JavaValueExpression.builder()//
                                                                                                                        .value("/authenticate/admin")//
                                                                                                                        .type(String.class)//
                                                                                                                        .build(),//
                                                                                                                JavaValueExpression.builder()//
                                                                                                                        .value("/signup")//
                                                                                                                        .type(String.class)//
                                                                                                                        .build(),//
                                                                                                                JavaValueExpression.builder()//
                                                                                                                        .value("/api/**")//
                                                                                                                        .type(String.class)//
                                                                                                                        .build()))//
                                                                                                        .build(),//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("permitAll")//
                                                                                                        .build(),//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("antMatchers")//
                                                                                                        .arguments(List.of(//
                                                                                                                JavaValueExpression.builder()//
                                                                                                                        .value("/admin/**")//
                                                                                                                        .type(String.class)//
                                                                                                                        .build()))//
                                                                                                        .build(),//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("hasAnyAuthority")//
                                                                                                        .arguments(List.of(//
                                                                                                                JavaValueExpression.builder()//
                                                                                                                        .value("ADMIN")//
                                                                                                                        .type(String.class)//
                                                                                                                        .build()))//
                                                                                                        .build(),//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("antMatchers")//
                                                                                                        .arguments(List.of(//
                                                                                                                JavaValueExpression.builder()//
                                                                                                                        .value("/user/**")//
                                                                                                                        .type(String.class)//
                                                                                                                        .build()))//
                                                                                                        .build(),//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("hasAnyAuthority")//
                                                                                                        .arguments(List.of(//
                                                                                                                JavaValueExpression.builder()//
                                                                                                                        .value("USER")//
                                                                                                                        .type(String.class)//
                                                                                                                        .build()))//
                                                                                                        .build(),//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("anyRequest")//
                                                                                                        .build(),//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("authenticated")//
                                                                                                        .build(),//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("and")//
                                                                                                        .build(),//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("exceptionHandling")//
                                                                                                        .build(),//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("authenticationEntryPoint")//
                                                                                                        .arguments(List.of(//
                                                                                                                JavaVariableExpression.builder()//
                                                                                                                        .variable("unauthorizedEntryPoint")//
                                                                                                                        .build()))//
                                                                                                        .build(),//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("and")//
                                                                                                        .build(),//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("sessionManagement")//
                                                                                                        .build(),//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("sessionCreationPolicy")//
                                                                                                        .arguments(List.of(//
                                                                                                                JavaValueExpression.builder()//
                                                                                                                        .value("org.springframework.security.config.http.SessionCreationPolicy.STATELESS")//
                                                                                                                        .type(SessionCreationPolicy.class)//
                                                                                                                        .build()))//
                                                                                                        .build()))//
                                                                                        .build())//
                                                                                .build(),//
                                                                        JavaExpressionStatement.builder()//
                                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                                        .target("http")//
                                                                                        .invokes(List.of(//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("addFilterBefore")//
                                                                                                        .arguments(List.of(//
                                                                                                                JavaVariableExpression.builder()//
                                                                                                                        .variable("jwtAuthenticationFilter")//
                                                                                                                        .build(),//
                                                                                                                JavaValueExpression.builder()//
                                                                                                                        .value("org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter")//
                                                                                                                        .type(Class.class)//
                                                                                                                        .build()))//
                                                                                                        .build()))//
                                                                                        .build())//
                                                                                .build()))//
                                                                .build(),//
                                                        JavaMethodDeclaration.builder()
                                                                .name("encoder")//
                                                                .returnType("org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder")//
                                                                .modifiers(JavaModifier.builder()//
                                                                        .type(JavaModifier.METHOD_MODIFIERS)//
                                                                        .modifiers(Modifier.PUBLIC)//
                                                                        .build())//
                                                                .annotations(List.of(//
                                                                        JavaAnnotation.builder()//
                                                                                .name("org.springframework.context.annotation.Bean")//
                                                                                .build()))//
                                                                .statements(List.of(//
                                                                        JavaReturnStatement.builder()//
                                                                                .expression(JavaNewInstanceExpression.builder()//
                                                                                        .name("org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder")//
                                                                                        .build())//
                                                                                .build()))//
                                                                .build(),//
                                                        JavaMethodDeclaration.builder()
                                                                .name("authenticationManagerBean")//
                                                                .returnType("org.springframework.security.authentication.AuthenticationManager")//
                                                                .modifiers(JavaModifier.builder()//
                                                                        .type(JavaModifier.METHOD_MODIFIERS)//
                                                                        .modifiers(Modifier.PUBLIC)//
                                                                        .build())//
                                                                .isThrows(true)//
                                                                .exceptions(List.of(//
                                                                        "Exception"))//
                                                                .annotations(List.of(//
                                                                        JavaAnnotation.builder()//
                                                                                .name("Override")//
                                                                                .build(),//
                                                                        JavaAnnotation.builder()//
                                                                                .name("org.springframework.context.annotation.Bean")//
                                                                                .build()))//
                                                                .statements(List.of(//
                                                                        JavaReturnStatement.builder()//
                                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                                        .target("super")//
                                                                                        .invokes(List.of(//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("authenticationManagerBean")//
                                                                                                        .build()))//
                                                                                        .build())//
                                                                                .build()))//
                                                                .build()))//
                                                .build()))//
                        .build(),//
                JavaCompilationUnit.builder()//
                        .packageName("website.smoothy.".concat(name.toLowerCase()).concat(".security"))//
                        .name("UnauthorizedEntryPoint")//
                        .typeDeclarations(
                                List.of(//
                                        JavaTypeDeclaration.builder()//
                                                .type(JavaType.CLASS)//
                                                .name("UnauthorizedEntryPoint")//
                                                .modifiers(JavaModifier.builder()//
                                                        .type(JavaModifier.TYPE_MODIFIERS)//
                                                        .modifiers(Modifier.PUBLIC | Modifier.FINAL)//
                                                        .build())//
                                                .implementedClassName("org.springframework.security.web.AuthenticationEntryPoint")//
                                                .annotations(List.of(//
                                                        JavaAnnotation.builder()//
                                                                .name("org.springframework.stereotype.Component")//
                                                                .build(),//
                                                        JavaAnnotation.builder()//
                                                                .name("lombok.extern.slf4j.Slf4j")//
                                                                .build()))//
                                                .methodDeclarations(List.of(//
                                                        JavaMethodDeclaration.builder()//
                                                                .name("commence")//
                                                                .returnType("void")//
                                                                .modifiers(JavaModifier.builder()//
                                                                        .type(JavaModifier.METHOD_MODIFIERS)//
                                                                        .modifiers(Modifier.PUBLIC)//
                                                                        .build())//
                                                                .isThrows(true)//
                                                                .exceptions(List.of(//
                                                                        "java.io.IOException"))//
                                                                .annotations(List.of(//
                                                                        JavaAnnotation.builder()//
                                                                                .name("org.springframework.context.annotation.Bean")//
                                                                                .build()))//
                                                                .parameters(List.of(//
                                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                                .name("request")//
                                                                                .type("javax.servlet.http.HttpServletRequest")//
                                                                                .build(),//
                                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                                .name("response")//
                                                                                .type("javax.servlet.http.HttpServletResponse")//
                                                                                .build(),//
                                                                        JavaMethodDeclaration.Parameter.builder()//
                                                                                .name("authException")//
                                                                                .type("org.springframework.security.core.AuthenticationException")//
                                                                                .build()))//
                                                                .statements(List.of(//
                                                                        JavaExpressionStatement.builder()//
                                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                                        .target("log")//
                                                                                        .invokes(List.of(//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("warn")//
                                                                                                        .arguments(List.of(//
                                                                                                                JavaBraceletExpression.builder()
                                                                                                                        .bracelet(false)//
                                                                                                                        .expressions(List.of(//
                                                                                                                                JavaValueExpression.builder()//
                                                                                                                                        .value("UnauthorizedEntryPoint.commence: path= ")//
                                                                                                                                        .type(String.class)//
                                                                                                                                        .operand(JavaOperand.PLUS)//
                                                                                                                                        .build(),//
                                                                                                                                JavaMethodInvocationExpression.builder()//
                                                                                                                                        .target("request")//
                                                                                                                                        .invokes(List.of(//
                                                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                                                        .method("getRequestURI")//
                                                                                                                                                        .build()))//
                                                                                                                                        .operand(JavaOperand.PLUS)//
                                                                                                                                        .build(),//
                                                                                                                                JavaValueExpression.builder()//
                                                                                                                                        .value(", ip= ")//
                                                                                                                                        .type(String.class)//
                                                                                                                                        .operand(JavaOperand.PLUS)//
                                                                                                                                        .build(),//
                                                                                                                                JavaMethodInvocationExpression.builder()//
                                                                                                                                        .target("request")//
                                                                                                                                        .invokes(List.of(//
                                                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                                                        .method("getRemoteAddr")//
                                                                                                                                                        .build()))//
                                                                                                                                        .operand(JavaOperand.PLUS)//
                                                                                                                                        .build(),//
                                                                                                                                JavaValueExpression.builder()//
                                                                                                                                        .value(", user agent= ")//
                                                                                                                                        .type(String.class)//
                                                                                                                                        .operand(JavaOperand.PLUS)//
                                                                                                                                        .build(),//
                                                                                                                                JavaMethodInvocationExpression.builder()//
                                                                                                                                        .target("request")//
                                                                                                                                        .invokes(List.of(//
                                                                                                                                                JavaMethodInvoke.builder()//
                                                                                                                                                        .method("getHeader")//
                                                                                                                                                        .arguments(List.of(//
                                                                                                                                                                JavaValueExpression.builder()//
                                                                                                                                                                        .value("User-Agent")//
                                                                                                                                                                        .type(String.class)//
                                                                                                                                                                        .build()))//
                                                                                                                                                        .build()))//
                                                                                                                                        .build()))//
                                                                                                                        .build()))//
                                                                                                        .build()))//
                                                                                        .build())//
                                                                                .build(),//
                                                                        JavaExpressionStatement.builder()//
                                                                                .expression(JavaMethodInvocationExpression.builder()//
                                                                                        .target("response")//
                                                                                        .invokes(List.of(//
                                                                                                JavaMethodInvoke.builder()//
                                                                                                        .method("sendError")//
                                                                                                        .arguments(List.of(//
                                                                                                                JavaValueExpression.builder()//
                                                                                                                        .value("javax.servlet.http.HttpServletResponse.SC_UNAUTHORIZED")//
                                                                                                                        .type(HttpServletResponse.class)//
                                                                                                                        .build()))//
                                                                                                        .build()))//
                                                                                        .build())//
                                                                                .build()))//
                                                                .build()))//
                                                .build()))//
                        .build());
    }

}
