//package solutions.thex.smoothy.generator.spring.main.src.java.security.jwt;
//
//import solutions.thex.smoothy.code.java.*;
//import solutions.thex.smoothy.code.java.declaration.JavaFieldDeclaration;
//import solutions.thex.smoothy.code.java.declaration.JavaMethodDeclaration;
//import solutions.thex.smoothy.code.java.source.JavaTypeDeclaration;
//import solutions.thex.smoothy.code.java.expression.JavaMethodInvocationExpression;
//import solutions.thex.smoothy.code.java.statement.JavaDeclarationStatement;
//import solutions.thex.smoothy.code.java.statement.JavaReturnStatement;
//
//import java.lang.reflect.Modifier;
//import java.util.List;
//
//public class JwtConfigsGenerators {
//
//    public static List<JavaCompilationUnit> generate(String name) {
//        return List.of(
//                JavaCompilationUnit.builder()//
//                        .packageName("website.smoothy.".concat(name.toLowerCase()).concat(".security.jwt"))//
//                        .name("Jwt")//
//                        .typeDeclarations(
//                                List.of(//
//                                        JavaTypeDeclaration.builder()//
//                                                .type(JavaType.CLASS)//
//                                                .name("Jwt")//
//                                                .modifiers(Modifier.PUBLIC)//
//                                                .implementedClassName("java.io.Serializable")//
//                                                .annotations(List.of(//
//                                                        Annotation.builder()//
//                                                                .name("org.springframework.stereotype.Component")//
//                                                                .build()))//
//                                                .fieldDeclarations(List.of(//
//                                                        JavaFieldDeclaration.builder()//
//                                                                .name("serialVersionUID")//
//                                                                .type("long")//
//                                                                .modifiers(Modifier.PRIVATE | Modifier.STATIC)//
//                                                                .initialized(true)//
//                                                                .value(new Long(-7644309794941483348L))
//                                                                .annotations(List.of(//
//                                                                        Annotation.builder()//
//                                                                                .name("java.io.Serial")//
//                                                                                .build()))//
//                                                                .build(),//
//                                                        JavaFieldDeclaration.builder()//
//                                                                .name("TOKEN_VALIDITY")//
//                                                                .type("long")//
//                                                                .modifiers(Modifier.PUBLIC)//
//                                                                .initialized(false)//
//                                                                .annotations(List.of(//
//                                                                        Annotation.builder()//
//                                                                                .name("org.springframework.beans.factory.annotation.Value")//
//                                                                                .attributes(List.of(//
//                                                                                        Annotation.Attribute.builder()//
//                                                                                                .type(String.class)//
//                                                                                                .values(List.of("${jwt.token.validity}"))//
//                                                                                                .build()))//
//                                                                                .build()))//
//                                                                .build(),//
//                                                        JavaFieldDeclaration.builder()//
//                                                                .name("SIGNING_KEY")//
//                                                                .type("String")//
//                                                                .modifiers(Modifier.PUBLIC)//
//                                                                .initialized(false)//
//                                                                .annotations(List.of(//
//                                                                        Annotation.builder()//
//                                                                                .name("org.springframework.beans.factory.annotation.Value")//
//                                                                                .attributes(List.of(//
//                                                                                        Annotation.Attribute.builder()//
//                                                                                                .type(String.class)//
//                                                                                                .values(List.of("{jwt.signing.key}"))//
//                                                                                                .build()))//
//                                                                                .build()))//
//                                                                .build(),//
//                                                        JavaFieldDeclaration.builder()//
//                                                                .name("AUTHORITIES_KEY")//
//                                                                .type("String")//
//                                                                .modifiers(Modifier.PUBLIC)//
//                                                                .initialized(false)//
//                                                                .annotations(List.of(//
//                                                                        Annotation.builder()//
//                                                                                .name("org.springframework.beans.factory.annotation.Value")//
//                                                                                .attributes(List.of(//
//                                                                                        Annotation.Attribute.builder()//
//                                                                                                .type(String.class)//
//                                                                                                .values(List.of("{jwt.authorities.key}"))//
//                                                                                                .build()))//
//                                                                                .build()))//
//                                                                .build()))//
//                                                .methodDeclarations(List.of(//
//                                                        JavaMethodDeclaration.builder()//
//                                                                .name("getUsernameFromToken")//
//                                                                .returnType("String")//
//                                                                .modifiers(Modifier.PUBLIC)//
//                                                                .parameters(List.of(//
//                                                                        Parameter.builder()//
//                                                                                .name("token")//
//                                                                                .type("String")//
//                                                                                .build()))//
//                                                                .statements(List.of(//
//                                                                        JavaReturnStatement.builder()//
//                                                                                .expression(JavaMethodInvocationExpression.builder()//
//                                                                                        .target("this")
//                                                                                        .invokes(List.of(//
//                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                        .method("getClaimFromToken")//
//                                                                                                        .arguments(List.of(//
//                                                                                                                Argument.builder()//
//                                                                                                                        .name("token")//
//                                                                                                                        .build(),//
//                                                                                                                Argument.builder()//
//                                                                                                                        .name("io.jsonwebtoken.Claims")//
//                                                                                                                        .invoked(true)//
//                                                                                                                        .lambda(true)//
//                                                                                                                        .invokes(List.of(//
//                                                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                                                        .method("getSubject")//
//                                                                                                                                        .lambda(true)//
//                                                                                                                                        .build()))//
//                                                                                                                        .build()))//
//                                                                                                        .build()))//
//                                                                                        .build())//
//                                                                                .build()))//
//                                                                .build(),//
//                                                        JavaMethodDeclaration.builder()//
//                                                                .name("getExpirationDateFromToken")//
//                                                                .returnType("java.util.Date")//
//                                                                .modifiers(Modifier.PUBLIC)//
//                                                                .parameters(List.of(//
//                                                                        Parameter.builder()//
//                                                                                .name("token")//
//                                                                                .type("String")//
//                                                                                .build()))//
//                                                                .statements(List.of(//
//                                                                        JavaReturnStatement.builder()//
//                                                                                .expression(JavaMethodInvocationExpression.builder()//
//                                                                                        .target("this")
//                                                                                        .invokes(List.of(//
//                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                        .method("getClaimFromToken")//
//                                                                                                        .arguments(List.of(//
//                                                                                                                Argument.builder()//
//                                                                                                                        .name("token")//
//                                                                                                                        .build(),//
//                                                                                                                Argument.builder()//
//                                                                                                                        .name("io.jsonwebtoken.Claims")//
//                                                                                                                        .invoked(true)//
//                                                                                                                        .lambda(true)//
//                                                                                                                        .invokes(List.of(//
//                                                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                                                        .method("getExpiration")//
//                                                                                                                                        .lambda(true)//
//                                                                                                                                        .build()))//
//                                                                                                                        .build()))//
//                                                                                                        .build()))//
//                                                                                        .build())//
//                                                                                .build()))//
//                                                                .build(),//
//                                                        JavaMethodDeclaration.builder()//
//                                                                .name("getClaimFromToken")//
//                                                                .returnType("<T> T")//
//                                                                .modifiers(Modifier.PUBLIC)//
//                                                                .parameters(List.of(//
//                                                                        Parameter.builder()//
//                                                                                .name("token")//
//                                                                                .type("String")//
//                                                                                .build(),//
//                                                                        Parameter.builder()//
//                                                                                .name("claimsResolver")//
//                                                                                .type("java.util.function.Function")//
//                                                                                .genericTypes(List.of("io.jsonwebtoken.Claims", "T"))//
//                                                                                .build()))//
//                                                                .statements(List.of(//
//                                                                        JavaDeclarationStatement.builder()//
//                                                                                .name("claims")//
//                                                                                .type("io.jsonwebtoken.Claims")//
//                                                                                .modifiers(Modifier.FINAL)//
//                                                                                .initialized(true)//
//                                                                                .expression(JavaMethodInvocationExpression.builder()//
//                                                                                        .target("this")
//                                                                                        .invokes(List.of(//
//                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                        .method("getAllClaimsFromToken")//
//                                                                                                        .arguments(List.of(//
//                                                                                                                Argument.builder()//
//                                                                                                                        .name("token")//
//                                                                                                                        .build()))//
//                                                                                                        .build()))//
//                                                                                        .build())
//                                                                                .build(),//
//                                                                        JavaReturnStatement.builder()//
//                                                                                .expression(JavaMethodInvocationExpression.builder()//
//                                                                                        .target("claimsResolver")
//                                                                                        .invokes(List.of(//
//                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                        .method("apply")//
//                                                                                                        .arguments(List.of(//
//                                                                                                                Argument.builder()//
//                                                                                                                        .name("claims")//
//                                                                                                                        .build()))//
//                                                                                                        .build()))//
//                                                                                        .build())//
//                                                                                .build()))//
//                                                                .build(),//
//                                                        JavaMethodDeclaration.builder()//
//                                                                .name("getAllClaimsFromToken")//
//                                                                .returnType("io.jsonwebtoken.Claims")//
//                                                                .modifiers(Modifier.PRIVATE)//
//                                                                .parameters(List.of(//
//                                                                        Parameter.builder()//
//                                                                                .name("token")//
//                                                                                .type("String")//
//                                                                                .build()))//
//                                                                .statements(List.of(//
//                                                                        JavaReturnStatement.builder()//
//                                                                                .expression(JavaMethodInvocationExpression.builder()//
//                                                                                        .target("io.jsonwebtoken.Jwts")
//                                                                                        .invokes(List.of(//
//                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                        .method("parser")//
//                                                                                                        .build(),//
//                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                        .method("setSigningKey")//
//                                                                                                        .arguments(List.of(//
//                                                                                                                Argument.builder()//
//                                                                                                                        .name("SIGNING_KEY")//
//                                                                                                                        .build()))//
//                                                                                                        .build(),//
//                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                        .method("parseClaimsJws")//
//                                                                                                        .arguments(List.of(//
//                                                                                                                Argument.builder()//
//                                                                                                                        .name("token")//
//                                                                                                                        .build()))//
//                                                                                                        .build(),//
//                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                        .method("getBody")//
//                                                                                                        .build()))//
//                                                                                        .build())//
//                                                                                .build()))//
//                                                                .build(),//
//                                                        JavaMethodDeclaration.builder()//
//                                                                .name("isTokenExpired")//
//                                                                .returnType("java.lang.Boolean")//
//                                                                .modifiers(Modifier.PRIVATE)//
//                                                                .parameters(List.of(//
//                                                                        Parameter.builder()//
//                                                                                .name("token")//
//                                                                                .type("java.lang.String")//
//                                                                                .build()))//
//                                                                .statements(List.of(//
//                                                                        JavaDeclarationStatement.builder()//
//                                                                                .name("expiration")//
//                                                                                .type("java.util.Date")//
//                                                                                .modifiers(Modifier.FINAL)//
//                                                                                .initialized(true)//
//                                                                                .expression(JavaMethodInvocationExpression.builder()//
//                                                                                        .target("this")//
//                                                                                        .invokes(List.of(//
//                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                        .method("getExpirationDateFromToken")//
//                                                                                                        .arguments(List.of(//
//                                                                                                                Argument.builder()//
//                                                                                                                        .name("token")//
//                                                                                                                        .build()))//
//                                                                                                        .build()))//
//                                                                                        .build())//
//                                                                                .build(),//
//                                                                        JavaReturnStatement.builder()//
//                                                                                .expression(JavaMethodInvocationExpression.builder()//
//                                                                                        .target("expiration")
//                                                                                        .invokes(List.of(//
//                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                        .method("before")//
//                                                                                                        .arguments(List.of(//
//                                                                                                                Argument.builder()//
//                                                                                                                        .name("java.util.Date")//
//                                                                                                                        .newed(true)//
//                                                                                                                        .build()))//
//                                                                                                        .build()))//
//                                                                                        .build())//
//                                                                                .build()))//
//                                                                .build(),//
//                                                        JavaMethodDeclaration.builder()//
//                                                                .name("generateToken")//
//                                                                .returnType("java.lang.String")//
//                                                                .modifiers(Modifier.PUBLIC)//
//                                                                .parameters(List.of(//
//                                                                        Parameter.builder()//
//                                                                                .name("authentication")//
//                                                                                .type("org.springframework.security.core.Authentication")//
//                                                                                .build()))//
//                                                                .statements(List.of(//
//                                                                        JavaDeclarationStatement.builder()//
//                                                                                .name("authorities")//
//                                                                                .type("java.lang.String")//
//                                                                                .initialized(true)//
//                                                                                .expression(JavaMethodInvocationExpression.builder()//
//                                                                                        .target("authentication")//
//                                                                                        .invokes(List.of(//
//                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                        .method("getAuthorities")//
//                                                                                                        .build(),//
//                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                        .method("stream")//
//                                                                                                        .build(),
//                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                        .method("map")//
//                                                                                                        .arguments(List.of(//
//                                                                                                                Argument.builder()//
//                                                                                                                        .name("org.springframework.security.core.GrantedAuthority")//
//                                                                                                                        .invoked(true)//
//                                                                                                                        .lambda(true)//
//                                                                                                                        .invokes(List.of(//
//                                                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                                                        .method("getAuthority")
//                                                                                                                                        .lambda(true)//
//                                                                                                                                        .build()))//
//                                                                                                                        .build()))//
//                                                                                                        .breakLine(true)//
//                                                                                                        .build(),
//                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                        .method("collect")//
//                                                                                                        .arguments(List.of(//
//                                                                                                                Argument.builder()//
//                                                                                                                        .name("java.util.stream.Collectors")//
//                                                                                                                        .invoked(true)//
//                                                                                                                        .invokes(List.of(//
//                                                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                                                        .method("joining")//
//                                                                                                                                        .arguments(List.of(//
//                                                                                                                                                Argument.builder()//
//                                                                                                                                                        .name("\",\"")//
//                                                                                                                                                        .build()))//
//                                                                                                                                        .build()))//
//                                                                                                                        .build()))//
//                                                                                                        .build()))//
//                                                                                        .build())//
//                                                                                .build(),//
//                                                                        JavaReturnStatement.builder()//
//                                                                                .expression(JavaMethodInvocationExpression.builder()//
//                                                                                        .target("io.jsonwebtoken.Jwts")
//                                                                                        .invokes(List.of(//
//                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                        .method("builder")//
//                                                                                                        .build(),//
//                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                        .method("setSubject")//
//                                                                                                        .arguments(List.of(//
//                                                                                                                Argument.builder()//
//                                                                                                                        .name("authentication")//
//                                                                                                                        .invoked(true)//
//                                                                                                                        .invokes(List.of(//
//                                                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                                                        .method("getName")//
//                                                                                                                                        .build()))//
//                                                                                                                        .build()))//
//                                                                                                        .build(),//
//                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                        .method("claim")//
//                                                                                                        .breakLine(true)//
//                                                                                                        .arguments(List.of(//
//                                                                                                                Argument.builder()//
//                                                                                                                        .name("AUTHORITIES_KEY")//
//                                                                                                                        .build(),//
//                                                                                                                Argument.builder()//
//                                                                                                                        .name("authorities")//
//                                                                                                                        .build()))//
//                                                                                                        .build(),//
//                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                        .method("setIssuedAt")//
//                                                                                                        .breakLine(true)//
//                                                                                                        .arguments(List.of(//
//                                                                                                                Argument.builder()//
//                                                                                                                        .name("java.util.Date")//
//                                                                                                                        .newed(true)//
//                                                                                                                        .invoked(true)//
//                                                                                                                        .invokes(List.of(//
//                                                                                                                                JavaMethodInvocationExpression.MethodInvoke.builder()//
//                                                                                                                                        .method("java.lang.System.currentTimeMillis")//
//                                                                                                                                        .build()))//
//                                                                                                                        .build()))//
//                                                                                                        .build()))//
//                                                                                        .build())//
//                                                                                .build()))//
//                                                                .build()))//
//                                                .build()))//
//                        .build());
//
//    }
//
//}
