package solutions.thex.smoothy.generator.spring.main.src.java.security.jwt;

import io.jsonwebtoken.SignatureAlgorithm;
import solutions.thex.smoothy.code.java.declaration.JavaFieldDeclaration;
import solutions.thex.smoothy.code.java.declaration.JavaMethodDeclaration;
import solutions.thex.smoothy.code.java.expression.*;
import solutions.thex.smoothy.code.java.expression.util.JavaMethodInvoke;
import solutions.thex.smoothy.code.java.source.JavaCompilationUnit;
import solutions.thex.smoothy.code.java.source.JavaTypeDeclaration;
import solutions.thex.smoothy.code.java.statement.JavaDeclarationStatement;
import solutions.thex.smoothy.code.java.statement.JavaReturnStatement;
import solutions.thex.smoothy.code.java.util.JavaAnnotation;
import solutions.thex.smoothy.code.java.util.JavaModifier;
import solutions.thex.smoothy.code.java.util.JavaOperand;
import solutions.thex.smoothy.code.java.util.JavaType;

import java.lang.reflect.Modifier;
import java.util.List;

public class JwtGenerator {

    public static JavaCompilationUnit generate(String name) {
        return JavaCompilationUnit.builder()//
                .packageName("website.smoothy.".concat(name.toLowerCase()).concat(".security.jwt"))//
                .name("Jwt")//
                .typeDeclarations(
                        List.of(//
                                JavaTypeDeclaration.builder()//
                                        .type(JavaType.CLASS)//
                                        .name("Jwt")//
                                        .modifiers(JavaModifier.builder()//
                                                .type(JavaModifier.TYPE_MODIFIERS)//
                                                .modifiers(Modifier.PUBLIC)//
                                                .build())//
                                        .implementedClassName("java.io.Serializable")//
                                        .annotations(List.of(//
                                                JavaAnnotation.builder()//
                                                        .name("org.springframework.stereotype.Component")//
                                                        .build()))//
                                        .fieldDeclarations(List.of(//
                                                JavaFieldDeclaration.builder()//
                                                        .name("serialVersionUID")//
                                                        .type("long")//
                                                        .modifiers(JavaModifier.builder()//
                                                                .type(JavaModifier.FIELD_MODIFIERS)//
                                                                .modifiers(Modifier.PRIVATE | Modifier.STATIC)//
                                                                .build())//
                                                        .initialized(true)//
                                                        .value(-7644309794941483348L)//
                                                        .annotations(List.of(//
                                                                JavaAnnotation.builder()//
                                                                        .name("java.io.Serial")//
                                                                        .build()))//
                                                        .build(),//
                                                JavaFieldDeclaration.builder()//
                                                        .name("TOKEN_VALIDITY")//
                                                        .type("long")//
                                                        .modifiers(JavaModifier.builder()//
                                                                .type(JavaModifier.FIELD_MODIFIERS)//
                                                                .modifiers(Modifier.PUBLIC)//
                                                                .build())//
                                                        .initialized(false)//
                                                        .annotations(List.of(//
                                                                JavaAnnotation.builder()//
                                                                        .name("org.springframework.beans.factory.annotation.Value")//
                                                                        .attributes(List.of(//
                                                                                JavaAnnotation.Attribute.builder()//
                                                                                        .type(String.class)//
                                                                                        .values(List.of("${jwt.token.validity}"))//
                                                                                        .build()))//
                                                                        .build()))//
                                                        .build(),//
                                                JavaFieldDeclaration.builder()//
                                                        .name("SIGNING_KEY")//
                                                        .type("String")//
                                                        .modifiers(JavaModifier.builder()//
                                                                .type(JavaModifier.FIELD_MODIFIERS)//
                                                                .modifiers(Modifier.PUBLIC)//
                                                                .build())//
                                                        .initialized(false)//
                                                        .annotations(List.of(//
                                                                JavaAnnotation.builder()//
                                                                        .name("org.springframework.beans.factory.annotation.Value")//
                                                                        .attributes(List.of(//
                                                                                JavaAnnotation.Attribute.builder()//
                                                                                        .type(String.class)//
                                                                                        .values(List.of("${jwt.signing.key}"))//
                                                                                        .build()))//
                                                                        .build()))//
                                                        .build(),//
                                                JavaFieldDeclaration.builder()//
                                                        .name("AUTHORITIES_KEY")//
                                                        .type("String")//
                                                        .modifiers(JavaModifier.builder()//
                                                                .type(JavaModifier.FIELD_MODIFIERS)//
                                                                .modifiers(Modifier.PUBLIC)//
                                                                .build())//
                                                        .initialized(false)//
                                                        .annotations(List.of(//
                                                                JavaAnnotation.builder()//
                                                                        .name("org.springframework.beans.factory.annotation.Value")//
                                                                        .attributes(List.of(//
                                                                                JavaAnnotation.Attribute.builder()//
                                                                                        .type(String.class)//
                                                                                        .values(List.of("${jwt.authorities.key}"))//
                                                                                        .build()))//
                                                                        .build()))//
                                                        .build()))//
                                        .methodDeclarations(List.of(//
                                                JavaMethodDeclaration.builder()//
                                                        .name("getUsernameFromToken")//
                                                        .returnType("String")//
                                                        .modifiers(JavaModifier.builder()//
                                                                .type(JavaModifier.METHOD_MODIFIERS)//
                                                                .modifiers(Modifier.PUBLIC)//
                                                                .build())//
                                                        .parameters(List.of(//
                                                                JavaMethodDeclaration.Parameter.builder()//
                                                                        .name("token")//
                                                                        .type("String")//
                                                                        .build()))//
                                                        .statements(List.of(//
                                                                JavaReturnStatement.builder()//
                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                .target("this")
                                                                                .invokes(List.of(//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("getClaimFromToken")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaVariableExpression.builder()//
                                                                                                                .variable("token")//
                                                                                                                .build(),//
                                                                                                        JavaLambdaMethodInvocationExpression.builder()//
                                                                                                                .target("io.jsonwebtoken.Claims")//
                                                                                                                .invoke("getSubject")//
                                                                                                                .build()))//
                                                                                                .build()))//
                                                                                .build())//
                                                                        .build()))//
                                                        .build(),//
                                                JavaMethodDeclaration.builder()//
                                                        .name("getExpirationDateFromToken")//
                                                        .returnType("java.util.Date")//
                                                        .modifiers(JavaModifier.builder()//
                                                                .type(JavaModifier.METHOD_MODIFIERS)//
                                                                .modifiers(Modifier.PUBLIC)//
                                                                .build())//
                                                        .parameters(List.of(//
                                                                JavaMethodDeclaration.Parameter.builder()//
                                                                        .name("token")//
                                                                        .type("String")//
                                                                        .build()))//
                                                        .statements(List.of(//
                                                                JavaReturnStatement.builder()//
                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                .target("this")
                                                                                .invokes(List.of(//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("getClaimFromToken")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaVariableExpression.builder()//
                                                                                                                .variable("token")//
                                                                                                                .build(),//
                                                                                                        JavaLambdaMethodInvocationExpression.builder()//
                                                                                                                .target("io.jsonwebtoken.Claims")//
                                                                                                                .invoke("getExpiration")//
                                                                                                                .build()))//
                                                                                                .build()))//
                                                                                .build())//
                                                                        .build()))//
                                                        .build(),//
                                                JavaMethodDeclaration.builder()//
                                                        .name("getClaimFromToken")//
                                                        .returnType("<T> T")//
                                                        .modifiers(JavaModifier.builder()//
                                                                .type(JavaModifier.METHOD_MODIFIERS)//
                                                                .modifiers(Modifier.PUBLIC)//
                                                                .build())//
                                                        .parameters(List.of(//
                                                                JavaMethodDeclaration.Parameter.builder()//
                                                                        .name("token")//
                                                                        .type("String")//
                                                                        .build(),//
                                                                JavaMethodDeclaration.Parameter.builder()//
                                                                        .name("claimsResolver")//
                                                                        .type("java.util.function.Function")//
                                                                        .genericTypes(List.of("io.jsonwebtoken.Claims", "T"))//
                                                                        .build()))//
                                                        .statements(List.of(//
                                                                JavaDeclarationStatement.builder()//
                                                                        .name("claims")//
                                                                        .type("io.jsonwebtoken.Claims")//
                                                                        .modifiers(JavaModifier.builder()//
                                                                                .type(JavaModifier.FIELD_MODIFIERS)//
                                                                                .modifiers(Modifier.FINAL)//
                                                                                .build())//
                                                                        .initialized(true)//
                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                .target("this")
                                                                                .invokes(List.of(//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("getAllClaimsFromToken")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaVariableExpression.builder()//
                                                                                                                .variable("token")//
                                                                                                                .build()))//
                                                                                                .build()))//
                                                                                .build())
                                                                        .build(),//
                                                                JavaReturnStatement.builder()//
                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                .target("claimsResolver")
                                                                                .invokes(List.of(//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("apply")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaVariableExpression.builder()//
                                                                                                                .variable("claims")//
                                                                                                                .build()))//
                                                                                                .build()))//
                                                                                .build())//
                                                                        .build()))//
                                                        .build(),//
                                                JavaMethodDeclaration.builder()//
                                                        .name("getAllClaimsFromToken")//
                                                        .returnType("io.jsonwebtoken.Claims")//
                                                        .modifiers(JavaModifier.builder()//
                                                                .type(JavaModifier.METHOD_MODIFIERS)//
                                                                .modifiers(Modifier.PRIVATE)//
                                                                .build())//
                                                        .parameters(List.of(//
                                                                JavaMethodDeclaration.Parameter.builder()//
                                                                        .name("token")//
                                                                        .type("String")//
                                                                        .build()))//
                                                        .statements(List.of(//
                                                                JavaReturnStatement.builder()//
                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                .target("io.jsonwebtoken.Jwts")
                                                                                .invokes(List.of(//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("parser")//
                                                                                                .build(),//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("setSigningKey")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaVariableExpression.builder()//
                                                                                                                .variable("SIGNING_KEY")//
                                                                                                                .build()))//
                                                                                                .build(),//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("parseClaimsJws")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaVariableExpression.builder()//
                                                                                                                .variable("token")//
                                                                                                                .build()))//
                                                                                                .build(),//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("getBody")//
                                                                                                .build()))//
                                                                                .build())//
                                                                        .build()))//
                                                        .build(),//
                                                JavaMethodDeclaration.builder()//
                                                        .name("isTokenExpired")//
                                                        .returnType("java.lang.Boolean")//
                                                        .modifiers(JavaModifier.builder()//
                                                                .type(JavaModifier.METHOD_MODIFIERS)//
                                                                .modifiers(Modifier.PRIVATE)//
                                                                .build())//
                                                        .parameters(List.of(//
                                                                JavaMethodDeclaration.Parameter.builder()//
                                                                        .name("token")//
                                                                        .type("java.lang.String")//
                                                                        .build()))//
                                                        .statements(List.of(//
                                                                JavaDeclarationStatement.builder()//
                                                                        .name("expiration")//
                                                                        .type("java.util.Date")//
                                                                        .modifiers(JavaModifier.builder()//
                                                                                .type(JavaModifier.FIELD_MODIFIERS)//
                                                                                .modifiers(Modifier.FINAL)//
                                                                                .build())//
                                                                        .initialized(true)//
                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                .target("this")//
                                                                                .invokes(List.of(//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("getExpirationDateFromToken")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaVariableExpression.builder()//
                                                                                                                .variable("token")//
                                                                                                                .build()))//
                                                                                                .build()))//
                                                                                .build())//
                                                                        .build(),//
                                                                JavaReturnStatement.builder()//
                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                .target("expiration")
                                                                                .invokes(List.of(//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("before")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaNewInstanceExpression.builder()//
                                                                                                                .name("java.util.Date")//
                                                                                                                .build()))//
                                                                                                .build()))//
                                                                                .build())//
                                                                        .build()))//
                                                        .build(),//
                                                JavaMethodDeclaration.builder()//
                                                        .name("generateToken")//
                                                        .returnType("java.lang.String")//
                                                        .modifiers(JavaModifier.builder()//
                                                                .type(JavaModifier.METHOD_MODIFIERS)//
                                                                .modifiers(Modifier.PUBLIC)//
                                                                .build())//
                                                        .parameters(List.of(//
                                                                JavaMethodDeclaration.Parameter.builder()//
                                                                        .name("authentication")//
                                                                        .type("org.springframework.security.core.Authentication")//
                                                                        .build()))//
                                                        .statements(List.of(//
                                                                JavaDeclarationStatement.builder()//
                                                                        .name("authorities")//
                                                                        .type("java.lang.String")//
                                                                        .initialized(true)//
                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                .target("authentication")//
                                                                                .invokes(List.of(//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("getAuthorities")//
                                                                                                .build(),//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("stream")//
                                                                                                .build(),
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("map")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaLambdaMethodInvocationExpression.builder()//
                                                                                                                .target("org.springframework.security.core.GrantedAuthority")//
                                                                                                                .invoke("getAuthority")//
                                                                                                                .build()))//
                                                                                                .build(),
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("collect")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaMethodInvocationExpression.builder()//
                                                                                                                .target("java.util.stream.Collectors")//
                                                                                                                .invokes(List.of(//
                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                .method("joining")//
                                                                                                                                .arguments(List.of(//
                                                                                                                                        JavaValueExpression.builder()//
                                                                                                                                                .value(",")//
                                                                                                                                                .type(String.class)//
                                                                                                                                                .build()))//
                                                                                                                                .build()))//
                                                                                                                .build()))//
                                                                                                .build()))//
                                                                                .build())//
                                                                        .build(),//
                                                                JavaReturnStatement.builder()//
                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                .target("io.jsonwebtoken.Jwts")
                                                                                .invokes(List.of(//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("builder")//
                                                                                                .build(),//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("setSubject")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaMethodInvocationExpression.builder()//
                                                                                                                .target("authentication")//
                                                                                                                .invokes(List.of(//
                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                .method("getName")//
                                                                                                                                .build()//
                                                                                                                ))//
                                                                                                                .build()))//
                                                                                                .build(),//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("claim")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaVariableExpression.builder()//
                                                                                                                .variable("AUTHORITIES_KEY")//
                                                                                                                .build(),//
                                                                                                        JavaVariableExpression.builder()//
                                                                                                                .variable("authorities")//
                                                                                                                .build()))//
                                                                                                .build(),//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("setIssuedAt")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaNewInstanceExpression.builder()//
                                                                                                                .name("java.util.Date")//
                                                                                                                .arguments(List.of(//
                                                                                                                        JavaMethodInvocationExpression.builder()//
                                                                                                                                .target("java.lang.System")//
                                                                                                                                .invokes(List.of(//
                                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                                .method("currentTimeMillis")//
                                                                                                                                                .build()))//
                                                                                                                                .build()))//
                                                                                                                .build()))//
                                                                                                .build(),//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("setExpiration")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaNewInstanceExpression.builder()//
                                                                                                                .name("java.util.Date")//
                                                                                                                .arguments(List.of(//
                                                                                                                        JavaBraceletExpression.builder()//
                                                                                                                                .bracelet(false)//
                                                                                                                                .expressions(List.of(//
                                                                                                                                        JavaMethodInvocationExpression.builder()//
                                                                                                                                                .target("java.lang.System")//
                                                                                                                                                .invokes(List.of(//
                                                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                                                .method("currentTimeMillis")//
                                                                                                                                                                .build()))//
                                                                                                                                                .operand(JavaOperand.PLUS)//
                                                                                                                                                .build(),//
                                                                                                                                        JavaVariableExpression.builder()//
                                                                                                                                                .variable("TOKEN_VALIDITY")//
                                                                                                                                                .operand(JavaOperand.MULTIPLY)//
                                                                                                                                                .build(),//
                                                                                                                                        JavaValueExpression.builder()//
                                                                                                                                                .value("1000")//
                                                                                                                                                .type(Integer.class)//
                                                                                                                                                .build()))//
                                                                                                                                .build()))//
                                                                                                                .build()))//
                                                                                                .build(),//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("signWith")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaValueExpression.builder()//
                                                                                                                .value("io.jsonwebtoken.SignatureAlgorithm.HS256")//
                                                                                                                .type(SignatureAlgorithm.class)//
                                                                                                                .build(),//
                                                                                                        JavaVariableExpression.builder()//
                                                                                                                .variable("SIGNING_KEY")//
                                                                                                                .build()))//
                                                                                                .build(),//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("compact")//
                                                                                                .build()))//
                                                                                .build())//
                                                                        .build()))//
                                                        .build(),//
                                                JavaMethodDeclaration.builder()//
                                                        .name("validateToken")//
                                                        .returnType("java.lang.Boolean")//
                                                        .modifiers(JavaModifier.builder()//
                                                                .type(JavaModifier.METHOD_MODIFIERS)//
                                                                .modifiers(Modifier.PUBLIC)//
                                                                .build())//
                                                        .parameters(List.of(//
                                                                JavaMethodDeclaration.Parameter.builder()//
                                                                        .name("token")//
                                                                        .type("java.lang.String")//
                                                                        .build(),//
                                                                JavaMethodDeclaration.Parameter.builder()//
                                                                        .name("userDetails")//
                                                                        .type("org.springframework.security.core.userdetails.UserDetails")//
                                                                        .build()))//
                                                        .statements(List.of(//
                                                                JavaDeclarationStatement.builder()//
                                                                        .name("username")//
                                                                        .type("java.lang.String")//
                                                                        .modifiers(JavaModifier.builder()//
                                                                                .type(JavaModifier.FIELD_MODIFIERS)//
                                                                                .modifiers(Modifier.FINAL)//
                                                                                .build())//
                                                                        .initialized(true)//
                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                .target("this")//
                                                                                .invokes(List.of(//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("getUsernameFromToken")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaVariableExpression.builder()//
                                                                                                                .variable("token")//
                                                                                                                .build()))//
                                                                                                .build()))//
                                                                                .build())//
                                                                        .build(),//
                                                                JavaReturnStatement.builder()//
                                                                        .expression(JavaBraceletExpression.builder()//
                                                                                .expressions(List.of(//
                                                                                        JavaMethodInvocationExpression.builder()//
                                                                                                .target("username")//
                                                                                                .invokes(List.of(//
                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                .method("equals")//
                                                                                                                .arguments(List.of(//
                                                                                                                        JavaMethodInvocationExpression.builder()//
                                                                                                                                .target("userDetails")//
                                                                                                                                .invokes(List.of(//
                                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                                .method("getUsername")//
                                                                                                                                                .build()))//
                                                                                                                                .build()))//
                                                                                                                .build()))//
                                                                                                .operand(JavaOperand.AND)//
                                                                                                .build(),//
                                                                                        JavaMethodInvocationExpression.builder()//
                                                                                                .target("this")//
                                                                                                .invokes(List.of(//
                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                .method("isTokenExpired")//
                                                                                                                .arguments(List.of(//
                                                                                                                        JavaVariableExpression.builder()//
                                                                                                                                .variable("token")//
                                                                                                                                .build()))//
                                                                                                                .build()))//
                                                                                                .operand(JavaOperand.NOT)//
                                                                                                .build()))//
                                                                                .build())//
                                                                        .build()))//
                                                        .build(),//
                                                JavaMethodDeclaration.builder()//
                                                        .name("getAuthenticationToken")//
                                                        .returnType("org.springframework.security.authentication.UsernamePasswordAuthenticationToken")//
                                                        .modifiers(JavaModifier.builder()//
                                                                .type(JavaModifier.METHOD_MODIFIERS)//
                                                                .modifiers(Modifier.PUBLIC)//
                                                                .build())//
                                                        .parameters(List.of(//
                                                                JavaMethodDeclaration.Parameter.builder()//
                                                                        .name("token")//
                                                                        .type("java.lang.String")//
                                                                        .modifiers(JavaModifier.builder()//
                                                                                .type(JavaModifier.FIELD_MODIFIERS)//
                                                                                .modifiers(Modifier.FINAL)//
                                                                                .build())//
                                                                        .build(),//
                                                                JavaMethodDeclaration.Parameter.builder()//
                                                                        .name("existingAuth")//
                                                                        .type("org.springframework.security.core.Authentication")//
                                                                        .modifiers(JavaModifier.builder()//
                                                                                .type(JavaModifier.FIELD_MODIFIERS)//
                                                                                .modifiers(Modifier.FINAL)//
                                                                                .build())//
                                                                        .build(),//
                                                                JavaMethodDeclaration.Parameter.builder()//
                                                                        .name("userDetails")//
                                                                        .type("org.springframework.security.core.userdetails.UserDetails")//
                                                                        .modifiers(JavaModifier.builder()//
                                                                                .type(JavaModifier.FIELD_MODIFIERS)//
                                                                                .modifiers(Modifier.FINAL)//
                                                                                .build())//
                                                                        .build()))//
                                                        .statements(List.of(//
                                                                JavaDeclarationStatement.builder()//
                                                                        .name("jwtParser")//
                                                                        .type("io.jsonwebtoken.JwtParser")//
                                                                        .modifiers(JavaModifier.builder()//
                                                                                .type(JavaModifier.FIELD_MODIFIERS)//
                                                                                .modifiers(Modifier.FINAL)//
                                                                                .build())//
                                                                        .initialized(true)//
                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                .target("io.jsonwebtoken.Jwts")//
                                                                                .invokes(List.of(//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("parser")//
                                                                                                .build(),//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("setSigningKey")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaVariableExpression.builder()//
                                                                                                                .variable("SIGNING_KEY")//
                                                                                                                .build()))//
                                                                                                .build()))//
                                                                                .build())//
                                                                        .build(),//
                                                                JavaDeclarationStatement.builder()//
                                                                        .name("claimsJws")//
                                                                        .type("io.jsonwebtoken.Jws")//
                                                                        .genericType(List.of("io.jsonwebtoken.Claims"))//
                                                                        .modifiers(JavaModifier.builder()//
                                                                                .type(JavaModifier.FIELD_MODIFIERS)//
                                                                                .modifiers(Modifier.FINAL)//
                                                                                .build())//
                                                                        .initialized(true)//
                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                .target("jwtParser")//
                                                                                .invokes(List.of(//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("parseClaimsJws")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaVariableExpression.builder()//
                                                                                                                .variable("token")//
                                                                                                                .build()))//
                                                                                                .build()))//
                                                                                .build())//
                                                                        .build(),//
                                                                JavaDeclarationStatement.builder()//
                                                                        .name("claims")//
                                                                        .type("io.jsonwebtoken.Claims")//
                                                                        .modifiers(JavaModifier.builder()//
                                                                                .type(JavaModifier.FIELD_MODIFIERS)//
                                                                                .modifiers(Modifier.FINAL)//
                                                                                .build())//
                                                                        .initialized(true)//
                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                .target("claimsJws")//
                                                                                .invokes(List.of(//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("getBody")//
                                                                                                .build()))//
                                                                                .build())//
                                                                        .build(),//
                                                                JavaDeclarationStatement.builder()//
                                                                        .name("authorities")//
                                                                        .type("java.util.Collection")//
                                                                        .genericType(List.of("? extends GrantedAuthority"))//
                                                                        .modifiers(JavaModifier.builder()//
                                                                                .type(JavaModifier.FIELD_MODIFIERS)//
                                                                                .modifiers(Modifier.FINAL)//
                                                                                .build())//
                                                                        .initialized(true)//
                                                                        .expression(JavaMethodInvocationExpression.builder()//
                                                                                .target("java.util.Arrays")//
                                                                                .invokes(List.of(//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("stream")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaMethodInvocationExpression.builder()//
                                                                                                                .target("claims")//
                                                                                                                .invokes(List.of(//
                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                .method("get")//
                                                                                                                                .arguments(List.of(//
                                                                                                                                        JavaVariableExpression.builder()//
                                                                                                                                                .variable("AUTHORITIES_KEY")//
                                                                                                                                                .build()))//
                                                                                                                                .build(),//
                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                .method("toString")//
                                                                                                                                .build(),//
                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                .method("split")//
                                                                                                                                .arguments(List.of(//
                                                                                                                                        JavaValueExpression.builder()//
                                                                                                                                                .value(",")//
                                                                                                                                                .type(String.class)//
                                                                                                                                                .build()))//
                                                                                                                                .build()))//
                                                                                                                .build()))//
                                                                                                .build(),//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("map")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaLambdaMethodInvocationExpression.builder()//
                                                                                                                .target("org.springframework.security.core.authority.SimpleGrantedAuthority")//
                                                                                                                .invoke("new")//
                                                                                                                .build()))//
                                                                                                .build(),//
                                                                                        JavaMethodInvoke.builder()//
                                                                                                .method("collect")//
                                                                                                .arguments(List.of(//
                                                                                                        JavaMethodInvocationExpression.builder()//
                                                                                                                .target("java.util.stream.Collectors")//
                                                                                                                .invokes(List.of(//
                                                                                                                        JavaMethodInvoke.builder()//
                                                                                                                                .method("toList")//
                                                                                                                                .build()))//
                                                                                                                .build()))//
                                                                                                .build()))//
                                                                                .build())//
                                                                        .build(),//
                                                                JavaReturnStatement.builder()//
                                                                        .expression(JavaNewInstanceExpression.builder()//
                                                                                .name("org.springframework.security.authentication.UsernamePasswordAuthenticationToken")//
                                                                                .arguments(List.of(//
                                                                                        JavaVariableExpression.builder()//
                                                                                                .variable("userDetails")//
                                                                                                .build(),//
                                                                                        JavaValueExpression.builder()//
                                                                                                .value("")
                                                                                                .type(String.class)//
                                                                                                .build(),//
                                                                                        JavaVariableExpression.builder()//
                                                                                                .variable("authorities")//
                                                                                                .build()))//
                                                                                .build())//
                                                                        .build()))//
                                                        .build()))//
                                        .build()))//
                .build();
    }

}
