package solutions.thex.smoothy.generate.spring;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import solutions.thex.smoothy.generate.Application;
import solutions.thex.smoothy.core.description.java.JavaTypeDescription;

import java.io.OutputStream;
import java.util.ArrayList;
import java.util.List;

@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
public class SpringBootApplicationDescription implements Application {

    private String name;
    @Builder.Default
    private String description = "Generated by Smoothy EWB!";
    @Builder.Default
    private String javaVersion = "18";
    @Builder.Default
    private String springVersion = "2.6.6";
    @Builder.Default
    private String port = "8080";
    @Builder.Default
    private List<JavaTypeDescription> types = new ArrayList<>();

    @Override
    public void generate(OutputStream out) {
        SpringBootApplicationGenerator.generate(this, out);
    }

}
