package solutions.thex.smoothy.generate.spring;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import solutions.thex.smoothy.core.description.java.JavaTypeDescription;
import solutions.thex.smoothy.core.description.java.type.JavaDAOTypeDescription;
import solutions.thex.smoothy.core.description.java.type.JavaRepositoryTypeDescription;
import solutions.thex.smoothy.generate.Application;

import java.io.OutputStream;
import java.util.List;

@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
public class SpringBootApplicationDescription implements Application {

    private String name;
    @Builder.Default
    private String description = "Generated by Smoothy EWB!";
    @Builder.Default
    private String javaVersion = "18";
    @Builder.Default
    private String springVersion = "2.6.6";
    @Builder.Default
    private String port = "8080";
    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME,//
            property = "type",//
            visible = true)
    @JsonSubTypes({
            @JsonSubTypes.Type(value = JavaDAOTypeDescription.class, name = "DAO"),
            @JsonSubTypes.Type(value = JavaRepositoryTypeDescription.class, name = "REPOSITORY")
    }
    )
    private List<JavaTypeDescription> types;

    @Override
    public void generate(OutputStream out) {
        SpringBootApplicationGenerator.generate(this, out);
    }

}
